### ISSUE TITLE
Every 2nd boot, "different reports about installed GuestAdditions"

### ISSUE THREAD

**Issue by brendonrapp** [dotless-de/vagrant-vbguest#111]
OS X 10.9.1, VirtualBox 4.3.6, Vagrant 1.4.3.

Every _other_ boot of my VMs, I get the following:

```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (4.3.6) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
stdin: is not a tty
Starting the VirtualBox Guest Additions ...done.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
[a-test-3-brendon] The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
prevent things such as shared folders from working properly. If you see
shared folder errors, please make sure the guest additions within the
virtual machine match the version of VirtualBox you have installed on
your host and reload your VM.

Guest Additions Version: 4.2.0
VirtualBox Version: 4.3
```

When I `vagrant halt` the machine and `vagrant up` it again, then I get:

```
GuestAdditions 4.3.6 running --- OK.
```

Then `halt` and `up` again, and back to:

```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (4.3.6) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
stdin: is not a tty
Starting the VirtualBox Guest Additions ...done.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 4.3.6
Going on, assuming VBoxService is correct...
[a-test-3-brendon] The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
prevent things such as shared folders from working properly. If you see
shared folder errors, please make sure the guest additions within the
virtual machine match the version of VirtualBox you have installed on
your host and reload your VM.

Guest Additions Version: 4.2.0
VirtualBox Version: 4.3
```

And `halt` and `up` again, and back to the OK message.

Round and round it goes...

**Comment by eddiemoya** [comment]
```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.10
VBoxService inside the vm claims: 4.3.20
Going on, assuming VBoxService is correct...
GuestAdditions 4.3.20 running --- OK.
```

I am on OSX 10.7.5, using a config directly off the puphpet website, for a box containing Ubuntu Trusty 64.

**Comment by brendonrapp** [comment]
Somewhere along the line of updates to VirtualBox and/or vbguest, I stopped experiencing this issue. It has been a few months for me.

**Comment by HenrikBechmann** [comment]
I've just started getting 'GuestAdditions seems to be installed (4.3.26) correctly, but not running.' frequently but not all the time. It appears to be bogus -- probably a timing issue of some sort. 

invoking 'vagrant vbguest --status' immediately after the results in 'GuestAdditions 4.3.26 running --- OK.'.

vagrant 1.7.2, vagrant-vbguest 0.10, virtualbox 4.3.26

So for the moment I'll just invoke that test to make sure all is ok. Still, it's a bit annoying...

**Comment by travishaynes** [comment]
This is due to a bug in VirtualBox 4.3. If you install version 4.2 the problem goes away.

**Comment by HenrikBechmann** [comment]
thanks travis. seems to have improved with 4.3.28 (latest vb) over 4.3.26. iac nbd...

**Comment by neobyteUK** [comment]
FYI this problem exists for me on VirtualBox 5.0.

    Got different reports about installed GuestAdditions version:
    Virtualbox on your host claims:   4.3.10
    VBoxService inside the vm claims: 5.0.0
    Going on, assuming VBoxService is correct...
    GuestAdditions 5.0.0 running --- OK.

Every second boot ...

**Comment by Gerst20051** [comment]
:+1:

**Comment by casualuser** [comment]
:+1:

**Comment by HenrikBechmann** [comment]
~~~~
$ vagrant vbguest --status
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.20
VBoxService inside the vm claims: 5.0.10
Going on, assuming VBoxService is correct...
GuestAdditions 5.0.10 running --- OK.

$ vboxmanage --version
5.0.10r104061
~~~~

flaky, sometimes works, sometimes not; sometimes rebuilds, sometimes not

**Comment by HenrikBechmann** [comment]
I not that 

~~~~

vagrant@ubuntu-14:/opt$ ls
chef                       VBoxGuestAdditions-4.3.24  VBoxGuestAdditions-5.0.0
VBoxGuestAdditions-4.3.12  VBoxGuestAdditions-4.3.26  VBoxGuestAdditions-5.0.10
VBoxGuestAdditions-4.3.14  VBoxGuestAdditions-4.3.28  VBoxGuestAdditions-5.0.8
VBoxGuestAdditions-4.3.16  VBoxGuestAdditions-4.3.30

~~~~

show that the install procedure leaves old guest additions lying around. maybe not so good.

**Comment by mauricioabreu** [comment]
FYI this problem reappeared in the Virtualbox 5.0.10.
Installing the newest version (5.0.**12**) this problem goes away.

Here is [VirtualBox changelog](https://www.virtualbox.org/wiki/Changelog). I sincerely did not find what would fix this issue in the changelog.

**Comment by HenrikBechmann** [comment]
Yeah upgrading to 5.0.12 seemed to work. So far so good.

Oddly Virtualbox 5.0.10 didn't report an update was available when asked to check for updates. I had to go to the virtualbox site and fetch it manually.

Thanks @mauricioabreu!!

**Comment by mauricioabreu** [comment]
You are welcome @HenrikBechmann ! It seems to be a VirtualBox bug. This issue can be closed in my honest opinion.

**Comment by HenrikBechmann** [comment]
Agreed!

**Comment by HenrikBechmann** [comment]
Bad news -- still happening, but only occasionally. My impression is it happens most on a 'cold' start -- after computer has been asleep or down for a while, and so far once per session, then ok for the day. (These are not carefully recorded observations).

Here's the console output:

```
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.26
VBoxService inside the vm claims: 5.0.12
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (5.0.12) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.26
VBoxService inside the vm claims: 5.0.12
Going on, assuming VBoxService is correct...
stdin: is not a tty
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
bash: line 3: vboxadd: command not found
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.26
VBoxService inside the vm claims: 5.0.12
Going on, assuming VBoxService is correct...
stdin: is not a tty
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

Restarting VM to apply changes...
==> default: Attempting graceful shutdown of VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.26
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => /Users/henrikbechmann/Servers/mustertools/www
    default: /vagrant => /Users/henrikbechmann/Servers/mustertools
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
Henriks-MacBook-Pro:mustertools henrikbechmann$ vagrant vbguest --status
GuestAdditions 5.0.12 running --- OK.

```

**Comment by deviantintegral** [comment]
I've been running into this same problem over the past few weeks. Upgrading to Virtualbox 5.0.12 didn't help. I also completely cleaned all guest additions from inside a VM, reinstalled, and it's still throwing the service / vboxadd errors along with reinstalling the additions.

**Comment by AlennGK** [comment]
Same here under Windows X
'Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.6
VBoxService inside the vm claims: 5.0.12
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (5.0.12) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.6
VBoxService inside the vm claims: 5.0.12
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...'

**Comment by iq8al** [comment]
I'm getting this on `ubuntu 15.10` with `Vagrant 1.7.4` and `GuestAdditions 5.0.14 running --- OK.`. The below happens **every** time I run `$ vagrant up`

```
$ [~/devel/trusty]$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 => 8088 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.14 r105127
VBoxService inside the vm claims: 5.0.14
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (5.0.14) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.14 r105127
VBoxService inside the vm claims: 5.0.14
Going on, assuming VBoxService is correct...
stdin: is not a tty
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
bash: line 3: vboxadd: command not found
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.14 r105127
VBoxService inside the vm claims: 5.0.14
Going on, assuming VBoxService is correct...
stdin: is not a tty
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

Restarting VM to apply changes...
==> default: Attempting graceful shutdown of VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/x/devel/trusty
    default: /home/vagrant/shared => /home/x/devel/shared
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
$ [~/devel/trusty]$ 
```

**Comment by austerus** [comment]
Same as @iq8al 

First time I boot all looks good, after halting and going up again, the same happens each and every time!

**Comment by ZStelmo** [comment]
Yap it´s true :(

**Comment by neilgee** [comment]
Getting it on 5.0.20
```
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.16
VBoxService inside the vm claims: 5.0.20
Going on, assuming VBoxService is correct...
GuestAdditions 5.0.20 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.16
VBoxService inside the vm claims: 5.0.20
Going on, assuming VBoxService is correct...
```

**Comment by NeMO84** [comment]
Same on 5.0.20
```
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.0.20
Going on, assuming VBoxService is correct...
GuestAdditions 5.0.20 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.0.20
Going on, assuming VBoxService is correct...
```

**Comment by hesco** [comment]
Me too:
GuestAdditions versions on your host (5.0.20) and guest (5.0.16) do not match. 

shared mount does not work.  

Host: OS-X 10.10.5, Guest: SLES11sp4, Vagrant 1.8.1

**Comment by NeMO84** [comment]
I filled a separate issue here #213 that may be relevant to others and maybe this issue.

**Comment by Tecktron** [comment]
I too came across this issue of what I thought to be vbguest not installing properly with a fresh install of VBox 5.1 and Vagrant 1.8.5 on Ubuntu 16.04. 

My first issue (not directly related but thought I should note it) was that I was sharing a folder over the `/opt` directory (which is where the guest additions now installs to). This had never been an issue for me before, but something somewhere changed with these versions (I don't know what version I was using before, but they were pretty old). So I moved my share to `/opt/shared` and I can now get the machine to boot. 

I then came across this issue, the guest additions always being of different version (but they were install?!?), so after checking the output as suggested [here](https://github.com/dotless-de/vagrant-vbguest/issues/130#issuecomment-179291784) by @eXistenZNL I saw that it was in fact installed correctly and just being reported incorrectly. 

Moreover, I found that rebooting (using the [vagrant-reload](https://github.com/aidanns/vagrant-reload) plugin), after I've finished provisioning the first time round, did not report this issue. But when I vagrant up'd the next time after a shutdown, it did show up again. 

Well, this can be permanently fixed by running [this handy script](https://gist.github.com/NeMO84/95e93346e81dbb2b75dd677922addbda) written by @NeMO84 on the host machine, after the box has been built, to update the local listing since it appears that it's not be updated properly (as stated in the above comment, see #213 for the explanation).

That's it! Problem solved.

I hope this summary of things helps someone else out in my predicament. 
A big thanks to everyone here for all your hard work. It's greatly appreciated.

**Comment by jackyq2015** [comment]
I think the script you mentioned is to change the box.ovf file to correct the guest addition version.

**Comment by vdboor** [comment]
The error seems to be related to kernel module building errors. By trying the install manually from an ssh session, I noticed that the install only partially succeeded. It turns out that an old kernel config causes this. It ends with "Look at `/var/log/vboxadd-setup.log` to see what went wrong".
