### ISSUE TITLE
VBox 4.3.10 Guest Additions bug and auto_reboot

### ISSUE THREAD

**Issue by hkim823** [dotless-de/vagrant-vbguest#118]
So there is a bug in VirtualBox 4.3.10 

https://www.virtualbox.org/ticket/12879

I'm trying to write a script inside of my Vagrantfile that would take care of this and I have config.vbguest.auto_reboot = true and it seems to update my VirtualBox Guest Additions inside the VM from 4.2 to 4.3.10, but it does not reboot the VM, and thus when it tries to use vboxfs it times out and fails doing a vagrant up.  Subsequent vagrant ups work just fine.  

Any ideas how I can troubleshoot the auto_reboot flag?

**Comment by 6temes** [comment]
+1
