### ISSUE TITLE
vagrant plugin install vagrant-vbguest fails

### ISSUE THREAD

**Issue by HenrikBechmann** [dotless-de/vagrant-vbguest#126]
I get this error message:

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually 
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.2.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.2.1'` succeeds before bundling.
```

This is some kind of trap, as I can successfully install the specified version of nokogiri as exptecte, yet I keep getting the same error.

Any ideas?

**Comment by andela-mallan** [comment]
Quick fix!
I run `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-vbguest` as a temporary solution.
Let me know if it works.

**Comment by fadilmohd007** [comment]
> Quick fix!
> I run `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-vbguest` as a temporary solution.
> Let me know if it works.

No same error again
