### ISSUE TITLE
Guest Additions not detected or working

### ISSUE THREAD

**Issue by lerouxb** [dotless-de/vagrant-vbguest#130]
I'm running vagrant-vbguest with vagrant version 1.6.3 and virtualbox version 4.3.14 on OSX Mavericks with Ubuntu 14.04 as my guest OS.

Whenever I run `vagrant reload` I get:

```
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.10
VBoxService inside the vm claims: 4.3.14
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (4.3.14) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.10
VBoxService inside the vm claims: 4.3.14
Going on, assuming VBoxService is correct...
stdin: is not a tty
Starting the VirtualBox Guest Additions ...done.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.10
VBoxService inside the vm claims: 4.3.14
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.10
VBoxService inside the vm claims: 4.3.14
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
```

This doesn't seem possible, because my VirtualBox claims top be 4.3.14 in the "VirtualBox -> About VirtualBox" dialog. Things like shared folders appear to work OK, but the date/time keeps going completely out of sync (by hours and days) even though I'm running ntpd.

I then have to run the following script to get it back again because every watch script and just about every bit of networking code that uses some 3rd party service goes completely haywire:

```
/etc/init.d/ntp stop
ntpdate ntp.ubuntu.com # won't run with ntp running
/etc/init.d/ntp start
```

All I can think of is that this is a Guest Additions related issue.

I'm not sure if this is really a vagrant-vbguest, vagrant or virtualbox issue. Any ideas? I'm even considering somehow finding a way to automatically run nptdate every time my laptop wakes from sleep.

**Comment by hollodotme** [comment]
I had the same issue after upgrading to v5.0.0 of VirtualBox.

I tried the solutions of @mczepiel and @Dreyer (in that order) and ended up with:

`GuestAdditions seems to be installed (5.0.0) correctly, but not running.`
 
What finally did the job was:

 * Replacing the VBoxGuestAdditions.iso under `/Applications/VirtualBox.app/Contents/MacOS/` with [VBoxGuestAdditions_5.0.0.iso](http://download.virtualbox.org/virtualbox/5.0.0/VBoxGuestAdditions_5.0.0.iso)
 * Removing the faulty box from vagrant index and VirtualBox by executing  
`vagrant destory && vagrant box remove <boxname> --box-version <boxversion>`
 * Re-adding, re-importing and running the box by executing `vagrant up` 

**Result:**
```
==> default: Machine booted and ready!
GuestAdditions 5.0.0 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
```

**Comment by ralren** [comment]
@hollodotme, by <boxversion> do you mean the `guest version` such as `Installing Virtualbox Guest Additions 5.0.0 - guest version is 4.2.0`?

**Comment by Brade** [comment]
This gives new meaning to the concept of "annoying" -- having to resort to "vagrant destroy" is unacceptable. Is there no other way to get this under control?

Keep getting "Virtualbox on your host claims:   4.3.10" when the host CLEARLY shows "Name: /VirtualBox/GuestAdd/Version, value: 5.0.4, timestamp: 1442327663306783000, flags:" when doing a VBoxManage guestproperty enumerate... This is psychotic!

**Comment by tomor** [comment]
Brade, do you use vagrant-vbguest Plugin? Try to disable it... that is what helped to me now.
Vagrantfile config:
*config.vbguest.auto_update = false*
*config.vbguest.no_install = true*
*config.vbguest.no_remote = true*

Error which I had:
*vagrant up*
..
*Got different reports about installed GuestAdditions version:*
*Virtualbox on your host claims:   4.3.10*
*VBoxService inside the vm claims: 5.0.6*
*Going on, assuming VBoxService is correct...*

*bash: line 3: /etc/init.d/vboxadd: No such file or directory*
...

**Comment by Brade** [comment]
Actually I ended up getting a new laptop, and even on a NEW install of everything (vagrant and virtualbox) with NO plugins, I'm still getting this mismatch error. Just gonna throw up my hands and rue technology at this point.

**Comment by tomor** [comment]
Then maybe you can try installing guest additions as described here: https://gist.github.com/fernandoaleman/5083680
That's the second thing which I did ( just installed 5.0.6 iso and not 4.3). Unfortunately the command "sudo /etc/init.d/vboxadd setup" fails for me so I thought it was not helpful. But you can try... I think that hollodotme (three comments above) has a good point about what's wrong.

**Comment by v6** [comment]
:+1:

**Comment by warroyo** [comment]
@hollodotme's solution also fixed the issue for me

**Comment by eXistenZNL** [comment]
I have the same problem on a lot of my vagrant boxes. So I tried this:

1. Open two terminals
1. In the left one, type the `vboxmanage guestproperty get <uuid> /VirtualBox/GuestAdd/Version` command
1. See that this shows the correct version, in my case 5.0.14.
1. Now watch this command: `watch -n1 vboxmanage guestproperty get <uuid> /VirtualBox/GuestAdd/Version` .
1. In the right terminal, type vagrant reload.
1. During reload, the left terminal starts showing a older version again, 4.2.0 in my case.
1. During the vbguest check, the version returned by the left terminal is still 4.2.0, hence the whole `Virtualbox claims this and VBoxService claims that` thing.
1. About 10 seconds after the box is completely up again, the left terminal will show the correct version again (5.0.14 in my case)

My verdict: Virtualbox somehow stores what version the box is first brought up with, and if possible checks directly in the box the current version. Because of the vbguest check that happens during the early stage of booting, this direct check is not yet possible and VirtualBox returns the stored older version, hence the mismatch.

**Comment by mvbeek-oefenweb** [comment]
I observed the same behaviour as @eXistenZNL.

What fixed it for me was updating the box used in the `Vagrantfile` under `config.vm.box`, then destroying the vagrant and bringing it back up (the box will be downloaded again during `vagrant up`).

```
vagrant box remove opscode_ubuntu-14.04_chef-provisionerless;
vagrant destroy;
vagrant up;
```

**Comment by NeMO84** [comment]
I don't quite understand why the host version of VirtualBox is set as a guest property in the first place. Wouldn't this be difficult to manage when you upgrade VB and each guest has their own respective property that needs to be updated; assuming you more than one guest. 

Also, all guests may report different host values if they were created at different points in time when there were different host VB version running at that time.

**Comment by v6** [comment]
// , Is anyone here still getting this? I haven't seen it lately, but that doesn't mean it's gone from "the wilde".

**Comment by lisawoodruff** [comment]
I have also been having this problem recently after updating my laptop to Big Sur and updating VirtualBox, guest additions just won't cooperate. I was able to find a workaround through vagrant destroy (similar to mentioned above) but it worked several times the other day, and today appears to have reverted back to not detecting the correct version for no discernable reason and won't map shared drives.
