### ISSUE TITLE
ISO Autodetection on Archlinux

### ISSUE THREAD

**Issue by ak5** [dotless-de/vagrant-vbguest#135]
Hi!

I am running Archlinux and our [[community] package for the Virtualbox Guest Additions ISO](https://www.archlinux.org/packages/community/any/virtualbox-guest-iso/) installs the ISO to ```/usr/lib/virtualbox/additions/VBoxGuestAdditions.iso```. It's not a big issue, since one can simply

```bash
sudo ln -s /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso /usr/share/virtualbox
```

...but thought you might like to know. Let me also know if you want a PR.

**Comment by KingCrunch** [comment]
I'd propose to make the path configurable. Then the easiest solution for arch (I use both arch and ubuntu) would be to define the path in `~/.vagrant.d/Vagrantfile` for all instances

**Comment by fnordfish** [comment]
Finally, 0.11.0 looks in `/usr/lib/virtualbox/additions/VBoxGuestAdditions.iso` as well. Sorry, that it took me so long.

**Comment by michaelherold** [comment]
This is so much faster than it previously was, since it's no longer downloading the image. Thanks for the update!
