### ISSUE TITLE
Possible change closet Ubuntu geo-repo source before calling upgrade?

### ISSUE THREAD

**Issue by zanhsieh** [dotless-de/vagrant-vbguest#138]
Hi,

This issue I believe especially applies for Ubuntu version before 14.04. My current geo-location is Asia/Hong Hong. In general most images I could get from internet would point the default geo-location (USA, e.g. us.archive.ubuntu.com) which is better to point to local geo-resource (e.g. HK -> ftp.cuhk.edu.hk/pub/Linux) in /etc/apt/source.lst. Similar issues have been floating around in superuser & askubuntu for years:

http://askubuntu.com/questions/37753/how-can-i-get-apt-to-use-a-mirror-close-to-me-or-choose-a-faster-mirror
http://superuser.com/questions/463877/how-to-automatically-select-fast-mirror-for-apt-get

Note that CentOS does not have this issue since yum would pick the fastest mirror automatically. 

Anything could improve this would be appreciated. Thanks.

BTW, I did tried inline calling sed replace in Vagrant file but vbguest got run before that.

**Comment by lioramilbaum** [comment]
I have the same issue. Did you find a solution?

**Comment by mmodler** [comment]
+1 here - the us.archive mirrors where slow/down yesterday and we had serious problems to get new vm's up.

I also figured out inline calling sed replace in Vagrant file but as mentioned above - vbguest runs before that.

I'm not clear if vbguest is the right place to change sources list if wanted, or is there a plugin around to do it and which runs before vbguest?

**Comment by mmodler** [comment]
Addition: Here's the solution to change the sources file, but itwill run after vbguest.

https://coderwall.com/p/habdwg/speed-up-package-download-in-vagrant-boxes

**Comment by zanhsieh** [comment]
Guys,

Since I reported this issues for long time ago, I develop some workaround (not really solve this issue since I am not familiar with Ruby; and I am very sure you guys are pretty familiar with these below): 
1. Use cache https://github.com/fgrehm/vagrant-cachier
2. Turn off auto-update and find your spare of time to build / re-package / search an up-to-date box. (build = Packer / VeeWee; re-package = vagrant box repackage / vagrant package => vagrant box add <new box name> package.box; search = hashicorp atlas / vagrantcloud / vagrantbox.es) Of course there are some side-effects.
3. Build your own mirror.
