### ISSUE TITLE
CentOS Kernel-Devel issue

### ISSUE THREAD

**Issue by njt1982** [dotless-de/vagrant-vbguest#141]
I see that vbguest tries to install the same kernel-devel package as the active kernel. However for CentOS 6.5, once there is a kernel update available, it seems the old kernel-devel is no longer available. This causes vbguest to fail to install.

I am using the `chef/centos-6.5` base image, so have got around this in my Vagrantfile by doing:

```
class ChefCentosInstaller < VagrantVbguest::Installers::Linux
  def install(opts=nil, &block)
    communicate.sudo('sudo yum install -y kernel kernel-devel', opts, &block)
    # calling `super` will run the installation
    # also it takes care of uploading the right iso file into the box
    # and cleaning up afterward
    super
  end
end
```

And adding this into my vagrantfile configuration:

```
  config.vbguest.installer = ChefCentosInstaller
```

This forces both kernel and kernel-devel to update to the same version.

I suspect the issue is in https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/redhat.rb somewhere....

Is it too aggressive to force a base image to update kernel by default (on provision)?!

**Comment by TheLonelyGhost** [comment]
FYI, running into this same issue with CentOS 7.0 (from the official `chef/centos-7.0` box). Ended up working around it entirely by mounting the shared folder with NFS (Windows users can use SMB instead).

Since this is a workstation-specific issue, I placed it in the `~/.vagrant.d/Vagrantfile` file. It appears this is a [leftover from vagrant's v1 days](http://docs-v1.vagrantup.com/v1/docs/vagrantfile.html#vagrantfile_load_order), but still applies.

Not exactly a fix for this issue, but it's a temporary workaround for anyone else needing it.

**Comment by njt1982** [comment]
I can confirm the 6.6 box fixes this problem.

I still personally believe that the vbguest updater should ensure it has the latest kernel if it requires kernel-devel... and if it detects that kernel has been updated, it should reboot.

The fact it errors if it cannot update, to me, feels like a bug. ITs not impossible to update, it just needs to jump through a small hoop ;)

**Comment by saada** [comment]
@njt1982, I agree... The plugin should handle this seemlessly

**Comment by bbone87** [comment]
I ended up hacking together a plugin/middleware fix for this issue and figured I'd post it here in case anyone else is interested. Pretty sure there's a cleaner/better way to do this, but this solution worked for me for now. Just add this to the bottom of your Vagrantfile:

```ruby
module UpdateCentOSKernel
    class UpdateCentOSKernelPlugin < Vagrant.plugin('2')
        name 'update_centos_kernel_plugin'

        # update yum after first boot when provisioning
        action_hook(:update_yum, :machine_action_up) do |hook|
            hook.after(VagrantPlugins::ProviderVirtualBox::Action::CheckGuestAdditions, UpdateCentOSKernel::Middleware::KernelUpdater)
        end
    end

    module Middleware
        class KernelUpdater
            @@rebooted = {};

            def initialize(app, env)
                @app = app
            end

            def call(env)
                @env = env
                @vm = env[:machine]
                @ui = env[:ui]
                self.update_kernel()
            end

            def update_kernel()
                if !@@rebooted[@vm.id]
                    @@rebooted[@vm.id] = true

                    @ui.info 'Updating kernel'
                    @vm.communicate.sudo('yum install -y kernel kernel-devel') do |type, data|
                        if type == :stderr
                            @ui.error(data);
                        else
                            @ui.info(data);
                        end
                    end

                    self.reboot()
                end
            end

            def reboot()
                @ui.info('Rebooting after updating kernel')
                simle_reboot = Vagrant::Action::Builder.new.tap do |b|
                    b.use Vagrant::Action::Builtin::Call, Vagrant::Action::Builtin::GracefulHalt, :poweroff, :running do |env2, b2|
                        if !env2[:result]
                            b2.use VagrantPlugins::ProviderVirtualBox::Action::ForcedHalt
                        end
                    end

                    b.use VagrantPlugins::ProviderVirtualBox::Action::Boot
                    if defined?(Vagrant::Action::Builtin::WaitForCommunicator)
                        b.use Vagrant::Action::Builtin::WaitForCommunicator, [:starting, :running]
                    end
                    b.use VagrantVbguest::Middleware
                end
                @env[:action_runner].run(simle_reboot, @env)
            end
        end
    end
end
```

**Comment by christophermancini** [comment]
I modified the redhat.rb and got close, but couldn't automate the reboot / reload after the kernel update so that the module could finish installing the Guest Additions.

**Comment by kcd83** [comment]
I found a simple solution for the likes of `chef/centos-6.5`
```
vagrant plugin uninstall vagrant-vbguest
```
So I guess the issue for this plugin is that it optimistically tries to upgrade the guest additions but this can fail on some OS in situations where the old version would do just fine.

So maybe the plugin should be pessimistic by default (user's add this to `~/vagrant.d/Vagrantfile`)
```
config.vbguest.auto_update = false
```
Or it could automagically detect if upgrading will fail or try installing upgrade dependencies before uninstalling the existing version so it fails back to that

To the credit of this plugin the warning it gives is pretty good
```
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
The headers for the current running kernel were not found. If the following
module compilation fails then this could be the reason.
The missing package can be probably installed with
yum install kernel-devel-2.6.32-431.el6.x86_64

Building the main Guest Additions module[FAILED]
```

**Comment by davidjb** [comment]
Still an issue; this came up for the first time for me with a CentOS 6.7 box. Since #153 is closed, this should be too presumably.  As per the final comment on #153, did anyone attempt creating a plugin for updating the kernel?  A quick look at https://vagrant-lists.github.io/plugins.html suggests no.

Manually updating the kernel (or the box) isn't that much of a pain otherwise.

**Comment by martin-langhoff** [comment]
There's a better way - #223 .
