### ISSUE TITLE
Oracle's UEK is not handled properly

### ISSUE THREAD

**Issue by TobyHFerguson** [dotless-de/vagrant-vbguest#145]
Oracle Linux is binary compatible with RedHat, so shows up as a RedHat distro. However the default kernel is the UEK. This means that the update command should install the `kernel-uek-devel-$(uname -r)` package, not the `kernel-devel-$(uname -r)`.

**Comment by fnordfish** [comment]
I've created an experimental installer for Oracle Linux.
But all the boxes I've found have some kind of networking issue (can't connect to the outside).
Can you point me to a working base box or instruction how the network should be set up?

**Comment by TobyHFerguson** [comment]
Try one of these - its been a while since I've used them, but they should
work:

http://tobyhferguson.org/boxes/

On Thu, Oct 22, 2015 at 8:28 AM, Robert Schulze <notifications@github.com>
wrote:

> I've created an experimental installer for Oracle Linux.
> But all the boxes I've found have some kind of networking issue (can't
> connect to the outside).
> Can you point me to a working base box or instruction how the network
> should be set up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotless-de/vagrant-vbguest/issues/145#issuecomment-150261869>
> .
>



-- 
toby

**Comment by fnordfish** [comment]
Thanks for your input @TobyHFerguson, v0.11.0 got a dedicated oracle installer.
