### ISSUE TITLE
vbguest doesn't handle proxies

### ISSUE THREAD

**Issue by TobyHFerguson** [dotless-de/vagrant-vbguest#146]
My host environment (Oracle Linux) requires the use of proxies, and therefore so too does my guest environment (also Oracle Linux) - but vbguest has no settings to allow one to inject a proxy in, and therefore the yum update executed by vbguest fails :-(

The fix is to provide something like 'vbguest.proxy = WPAD or PROXY'  which will cause yum or its equivalent with other packaging mechanisms to use the correct proxy ...

**Comment by ilpianista** [comment]
Isn't this a duplicate of #77?

(I confirm vagrant-proxyconf solved the issue for me)
