### ISSUE TITLE
vagrant-vbguest plugin installation failure

### ISSUE THREAD

**Issue by JoAmala** [dotless-de/vagrant-vbguest#152]
I'm trying to setup a vagrant system for rails development in Windows.

My vagrant version is Vagrant 1.4.2 and I have installed both the plugins vagrant-librarian-chef (0.1.4) and vagrant-vbguest (0.10.0).

But when I do vagrant up I get the following error.

$ vagrant up

The plugin "vagrant-vbguest" could not be found. Please make sure that it is properly installed via vagrant plugin. Note that plugins made for Vagrant 1.0.x are not compatible with 1.1+ and this error will likely continue to show when you use plugin install with a 1.0.x plugin. Bringing machine 'default' up with 'virtualbox' provider... There are errors in the configuration of this machine. Please fix the following errors and try again:

vm: * The box 'base' could not be found.

**Comment by fnordfish** [comment]
Hello @JoAmala 

are there any reasons why you need to use Vagrant 1.4.2 and not upgrade?
Anyways, it looks like your gem configuration got messed up. Usual suspects are updates of vagrant, or using different installation methods (old "gem install" and new "download").
For more information have a look here: https://docs.vagrantup.com/v2/installation/index.html
To uninstall the RubyGem version on vagrant run `gem uninstall vagrant`.

To "clean up" messed up plugin installation I find it the easiest to install them from scratch:

0. run all `vagrant` commands **outside** of any vagrant project directory (e.g. home)
1. list what plugins you have installed and remember that list (`vagrant plugin list`)
2. rename (or delete) the place where vagrant puts it's dependencies and plugins (`mv ~/.vagrant.d/gems ~/.vagrant.d/gems_OLD`)
3. re-install vagrant by running the installer (just to make sure everything is in place)
4. re-install all the plugins from step 1
