### ISSUE TITLE
VirtualBox Guest Additions do not compile on Fedora 22 guest

### ISSUE THREAD

**Issue by jamesgecko** [dotless-de/vagrant-vbguest#158]
When installing guest additions onto a new Fedora 22 box, the kernel module fails to compile.

[vagrant up output](https://gist.github.com/jamesgecko/8cf785d015d3d5fac7d7#file-vagrant-up-output).

It's odd that it complains that `make` and `gcc` couldn't be found when it's clearly just installed them.

```
Building the VirtualBox Guest Additions kernel modules
The make utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.
 
The gcc utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.
 
Building the main Guest Additions module[FAILED]
(Look at /var/log/vboxadd-install.log to find out what went wrong)
Doing non-kernel setup of the Guest Additions[  OK  ]
```

There's also this error at the top of [/var/log/vboxadd-install.log](https://gist.github.com/jamesgecko/8cf785d015d3d5fac7d7#file-var-log-vboxadd-install-log)

```
grep: /lib/modules/4.0.4-301.fc22.x86_64/build/include/linux/version.h: No such file or directory
```

**Comment by simonschmidt** [comment]
It works for me, but I have to specify type for synced_folders or it uses rsync.
Here is the output I got:
https://gist.github.com/simonschmidt/787013e806bd2d9a571b

The Vagrantfile:
```ruby
BOX_NAME= "Fedora-Cloud-Base-Virtualbox-22"
BOX_URL = "https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = BOX_URL

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
```

```
$ vagrant --version
Vagrant 1.7.2
$ vagrant plugin list | grep vbguest
vagrant-vbguest (0.10.0)
$ VBoxManage --version
4.3.28r100309
```

**Comment by PatrickCoffey** [comment]
i had same issue! turned out DKMS wasnt installed by default (`dnf/yum install dkms`) i also went to the kernel source folder and did a `make oldconfig` too becuase in the logs it was complaining about that being missing.

**Comment by fnordfish** [comment]
Version 0.11.0 got a dedicated fedora installer which adds the `dkms` package as a dependency.
