### ISSUE TITLE
intermittent installation failure: No gems found matching "vagrant-vmware-workstation"

### ISSUE THREAD

**Issue by nikolas** [dotless-de/vagrant-vbguest#165]
I got this error running `vagrant plugin install vagrant-vbguest` on vagrant 1.7.4.

> Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

> Net::HTTPNotFound: No gems found matching "vagrant-vmware-workstation" "2.5.2" nil

> Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.

When I ran the command again, it worked. It would be nice if this error said something more along the lines of "try again, because it could be a network issue".

**Comment by fnordfish** [comment]
Hi @nikolas,
this is not a vagrant-vbguest issue, nor can this project do anything about it. The error accrues when vagrant runs Bundler (a ruby dependency management tool for ruby, which vagrant plugins depend on).
