### ISSUE TITLE
Enable configuring X drivers on basic installs

### ISSUE THREAD

**Issue by donv** [dotless-de/vagrant-vbguest#166]
Hi!

Great project!  Pardon my noobiness :)

I want to set up a vagrant box with Centos 7 and an X server.

I am using the "chef/centos-7.1" box, but I am not picky.  This box is without X server preinstalled, and I install Xorg using a shell provision block.  The X server will however not start without the virtualbox guest additions.

So I use this fine plugin to build the guest additions, but that happens before the other provisioning, so the drivers are not installed since Xorg has not been installed.

Any hint on how this can/should be done?  All help is appreciated.

**Comment by donv** [comment]
This seems to do the job:

```ruby
class XorgInstaller < VagrantVbguest::Installers::RedHat
  def install(opts=nil, &block)
    communicate.sudo('yum -y install xorg-x11-server-Xorg', opts, &block)
    super
  end
end

Vagrant.configure(2) do |config|
  config.vm.box = 'chef/centos-7.1'
  config.vbguest.installer = XorgInstaller
end
```

Is this a good way of doing it?

I am having trouble getting the mouse (trackpad) to work, but that is probably another issue.

**Comment by donv** [comment]
Changing the installer to the code below fixed the mouse as well:

```ruby
class XorgInstaller < VagrantVbguest::Installers::RedHat
  def install(opts=nil, &block)
    communicate.sudo('yum -y groupinstall "X Window system"', opts, &block)
    super
  end
end
```

Is this a good way to solve it?

**Comment by fnordfish** [comment]
Sorry for my late answer, but yes, your class looks good.
Although, if you plan to recreate your box frequently or share with some co-workers, it's probably a better idea to create a base-box which has all the X packages already installed.
