### ISSUE TITLE
CentOS7 needs bzip2

### ISSUE THREAD

**Issue by avinashkolluru** [dotless-de/vagrant-vbguest#167]
I see the code commit for it. When can I expect the release of the next version?

**Comment by yangm97** [comment]
+1

**Comment by chrisemerson** [comment]
same. Looks like no new version has been tagged since 2013...

**Comment by avinashkolluru** [comment]
Finally ended up created a new base box which has bzip2

https://atlas.hashicorp.com/avinashkolluru/boxes/centos7-1508.01-bzip2

Installed bzip2 over centos/7 box image

**Comment by dhampik** [comment]
+1 for adding bzip2 to installation

**Comment by flavio-fernandes** [comment]
+1, please publish new rev!

**Comment by gepoch** [comment]
:+1:

Is this project still active? This seems like too important of a plugin to have a 3 year old release..

**Comment by fnordfish** [comment]
Just released 0.10.1 which includes 'bzip2'.

**Comment by gepoch** [comment]
Thanks for the turnaround @fnordfish !
