### ISSUE TITLE
Could not fetch specs from http://gems.hashicorp.com/

### ISSUE THREAD

**Issue by lukehinds** [dotless-de/vagrant-vbguest#169]
Vagrant 1.7.4

Fedora 22

Virtual Box: 5.0.2

$ sudo vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from http://gems.hashicorp.com/

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.

    curl http://gems.hashicorp.com/

Resolves ok.

**Comment by fnordfish** [comment]
Sorry @lukehinds, this is not a vagrant-vbguest issue. The messages states:

> These errors are usually caused by misconfigured plugin installations or transient network issues

which is, dispute the successful "curl", most likely the probably the reason.

**Comment by dhawangupta** [comment]
Related:
http://stackoverflow.com/questions/33109186/how-to-install-the-proxy-plugin-behind-a-proxy-for-vagrant
