### ISSUE TITLE
VirtualBox 5.0.6 init script changes breaks vagrant-vbguest on systemd guests

### ISSUE THREAD

**Issue by gchaix** [dotless-de/vagrant-vbguest#170]
The [VirtualBox 5.0.6 Changelog](https://www.virtualbox.org/wiki/Changelog) shows:
> Linux hosts / guests: native systemd support for the host/guest installer scripts. The scripts for re-compiling the kernel modules are now located at /sbin/rcvboxdrv (host) and /sbin/rcvboxadd (Guest Additions)

Upgrading to 5.0.6 causes errors like the following on CentOS 7 guests:
```
GuestAdditions 5.0.6 running --- OK.
bash: line 3: /etc/init.d/vboxadd: No such file or directory
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/etc/init.d/vboxadd setup

Stdout from the command:



Stderr from the command:

bash: line 3: /etc/init.d/vboxadd: No such file or directory
```
and
```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

The kernel extension is built properly and the services installed by the plugin, but the service defaults to disabled:
```
[root@vagrant-multi1 vagrant]# service vboxadd status
Redirecting to /bin/systemctl status  vboxadd.service
vboxadd.service
   Loaded: loaded (/opt/VBoxGuestAdditions-5.0.6/init/vboxadd; disabled)
   Active: inactive (dead)
```

Enabling the service with `systemctl enable vboxadd` and restarting the guest resolves the issue until the next destroy/provision.

Patching the `start()` in installers/linux.rb is trivial, as `service` is backward-compatible on systemd.  So replacing `/etc/init.d/vboxadd start` with `service vboxadd start` should be effective on both systemd and traditional init systems.

Patching `rebuild()` in installers/linux.rb is a little trickier.  The script still exists in `/sbin/rcvboxadd`, but only on versions ≥5.0.6.

**Comment by darnells** [comment]
Until a coded fix is introduced, I am partially working around the issue by adding a simlink to the vboxadd script during provisioning.

```
# vagrant-vbguest 0.10.1 requirement
if [ ! -f /etc/init.d/vboxadd ]
then
  vboxadd=$(find /opt -name vboxadd | head -n 1)
  if [ -f "$vboxadd" ]
  then
    ln -s $vboxadd /etc/init.d
  fi
fi
```

**Comment by fnordfish** [comment]
Please check out v0.11.0 which now uses either `service`, `chkconfg` or "init.d" based on their availability on the host.
