### ISSUE TITLE
vagrant-vbguest cannot copy VBoxGuestAdditions.iso from the host to guest (device write-protected)

### ISSUE THREAD

**Issue by ferenczy** [dotless-de/vagrant-vbguest#173]
I'm having a weird issue. `vagrant-vbguest` plugin cannot copy the `VBoxGuestAdditions.iso` from the host to guest, because block device `/tmp` is write-protected. So it just installs the Guest Additions from ISO which is already there and which is the same version as the already installed one. It does that on every `vagrant up`.

I guess that an output of `vagrant up` command makes it more clear:

    ...
    GuestAdditions versions on your host (5.0.0) and guest (4.3.4) do not match.
    ...
    Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
    mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
    Installing Virtualbox Guest Additions 4.3.4 - guest version is 4.3.4
    ...
    Removing installed version 4.3.4 of VirtualBox Guest Additions...
    ...
    Building the VirtualBox Guest Additions kernel modules ...done.
    Doing non-kernel setup of the Guest Additions ...done.
    ...
    default: Guest Additions Version: 4.3.4
    default: VirtualBox Version: 5.0

So it basically removes and re-installs the same version of the Guest Additions every time VM is started.

What can be wrong with my setup?

**Comment by fnordfish** [comment]
Hi @ferenczy, it's very uncommon, that `/tmp` is write protected. What kind of guest system are you using? Os it some kind of "official" realese? If so, could you ask the creator of the base box if this is desired behavior.

**Comment by fnordfish** [comment]
In version 0.11.0 the `iso_upload_path` (defaults to `/tmp`) can now be overwritten.
