### ISSUE TITLE
Issue with opensuse implementation of guest additions

### ISSUE THREAD

**Issue by kunal30xi** [dotless-de/vagrant-vbguest#176]
We are running SUSE Linux Enterprise Server 11 (x86_64) PATCHLEVEL = 3 in our VM. We encountered an issue when one of the developers on our team upgraded to vagrant-vbguest plugin 0.11.0

We started getting the following stack trace when bringing the VM up. (see screenshot)

'kernel-devel' not found in package names. Trying capabilities.
No provider of 'kernel-devel' found.

![screenshot](https://cloud.githubusercontent.com/assets/5438564/11076121/10f07300-87c7-11e5-8162-17427b95f2f9.png)

We eventually tracked down the issue to a recent commit for #163 that was detecting and attempting to install a series of packages specific to openSUSE instead of the Generic Linux VBox Guest Additions. In our specific case it was failing when attempting to install "kernel-devel".

We've not had much luck locating the 'kernel-devel' package. We've found the following in our repositories:

kernel-default
kernel-default-base
kernel-default-devel

We identified 2 workarounds within our team (one better than the other). 

a) Download the VBoxGuestAdditions.iso thru wget, mount the iso and run VBoxLinuxAdditions.iso to get everything back to a working order
b) Add a constraint to our install script to use vagrant-vbguest 0.10.0 instead of 0.11.0 to ensure our environment continues to function as before. (USING THIS FOR NOW)

We want to continue to leverage the latest version of the vagrant-vbguest plugin so staying pinned to 0.10.0 is not a great long term option. With that in mind, any help would be greatly appreciated.

**Comment by derks** [comment]
Experiencing this same issue after updating plugins:

Vagrant: 1.7.4 and 1.8.1
VBGuest Plugin: 0.11.0
System: OSX
