### ISSUE TITLE
GuestAdditions version 5.0.10 r104061 false positive

### ISSUE THREAD

**Issue by razvanphp** [dotless-de/vagrant-vbguest#178]
Hello,

After the last upgrade of VirtualBox, the version detected got a version suffix, can this be fixed somehow?

```
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.10 r104061
VBoxService inside the vm claims: 5.0.10
Going on, assuming VBoxService is correct...
GuestAdditions 5.0.10 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.10 r104061
VBoxService inside the vm claims: 5.0.10
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
```

**Comment by NeMO84** [comment]
I just spent 1 hour debugging the source to eventually find this issue and realized that it had already been fixed but the latest release doesn't have the fix. I really wish GitHub best practices included using labels to signify pending version release or something. IMO, the concept of 'Closed' is too narrow/restrictive. 

But anyways, kudos on the fix. Thanks.
