### ISSUE TITLE
"binutils" package missing in redhat.rb installer

### ISSUE THREAD

**Issue by andy-maier** [dotless-de/vagrant-vbguest#188]
**Problem:**

The current `redhat.rb` installer defines a number of packages in its `dependencies` method.
Besides the widely discussed issue with `kernel-devel` for CentOS 6.7, 7.1 and 7.2 (see for example issue #161), that package list has the issue that it misses the `binutils` package.

That package provides the `libopcodes*.so` file which is needed by the assembler in the course of building the main module for Virtual Box Guest Additions. The assembler requires a particular version of `libopcodes*.so`, so if the installed version of the `binutils` package is too old, it fails.

**How to reproduce:**

I found this with problem with the `bento/centos-7.1` box. It comes with these packages:
  * kernel: 3.10.0-229.el7 (latest available: 3.10.0-327.3.1.el7)
  * kernel-devel: not installed (latest available: 3.10.0-327.3.1.el7)
  * binutils: 2.23.52.0.1-30.el7 (latest available: 2.23.52.0.1-55.el7)

I actually had some trouble reproducing this issue. It would go something like this:
- "up" the box freshly with `config.vbguest.no_install = true`,
- log in and manually update the packages `kernel` and `kernel-devel` (`kernel` needs to be updated because it needs to match `kernel-devel`, of which the older version is not available anymore in the CentOS repos (including CentOS Vault), and updating `kernel-devel` works around that issue),
- shut down,
- "up" the box with `config.vbguest.no_install = false`,
- Which should then fail when building the main VBGA module, with its log file indicating a missing `libopcodes-*.so`, trying to use its latest available version which is not installed.

However, when retrying it, building the VBGA worked fine. Maybe you can simply believe me that I saw the assembler failing because of an incorrect version of `libopcodes-*.so`. I ran into this when trying to circumvent the `kernel-devel` issue.

In any case, because `libopcodes-*.so` is undoubtedly used in the VBGA build process, and because `binutils` seems to be the only package providing that file, and because `binutils` is not a direct or indirect dependency of any of the other packages in the package list, `binutils` should be added to the dependent package list, IMO.

**Proposed solution:**

In the `dependencies`  method in `redhat.rb`, add the `binutils` package to the package list.

**Comment by fnordfish** [comment]
Thanks a lot for digging into this!
Included in 6600736

**Comment by fnordfish** [comment]
fixed in 0.12.0
