### ISSUE TITLE
vagrant: vbguest command not available

### ISSUE THREAD

**Issue by mmodler** [dotless-de/vagrant-vbguest#19]
I try to use vagrant-vbguest because it will hopefully solve some of my guest additions out of date issues :)

I use vagrant 1.0.3 on a windows host (installed from .msi) so plugin autoloading should still work. I installed vagrant-vbguest from my git-bash with "vagrant gem install", "vagrant gem list" shows that the plugin (0.3.3) is installed. And i have the plugin files in ~/.vagrant.d\gems\gems\vagrant-vbguest-0.3.3

When i try "vagrant help" on my git-bash, no vbguest is there. I'm not certain if this is a vagrant-vbguest issue or a general vagrant plugin issue. I'll post here first ;)

Regards from Grimma (Germany)

**Comment by austinbutler** [comment]
Yep, Babun works fine. Thanks for the recommendation!

**Comment by dragon788** [comment]
On Win7 without Babun I can also do `vagrant plugin install vagrant-vbguest` from a PowerShell or cmd prompt.
