### ISSUE TITLE
Vagrant up takes long time after installing guest additions manually. 

### ISSUE THREAD

**Issue by akaSStalkALEX** [dotless-de/vagrant-vbguest#192]
Not sure how to describe issue correctly. So I initialized centos/7 box, also I have vbguest plugin and it tried to install guest additions as usual during vagrant up command executing. Installation of one of the modules failed. I installed guest additions manually but before it yum update command was executed to fix building failed module. After these actions plugin showed GuestAdditions 5.0.12 running --- OK. But I get problem: vagrant up command executing time instead of seconds becomes almost 3-5 minutes. It started to hangs on booting machine, checking guest additions, mounting folders. I tried debug options and as I understand vagrant was not able to define version of virtual machine. There was long time loop before each command during "up" trying to sort out different versions of Linux(ubuntu, debian, arch, funtoo etc.) and also I saw error "failed connecting to ssh agent" something like that. Not sure if it is bug of vagrant or this plugin.

**Comment by fnordfish** [comment]
Hi,

actually, I don't thing it's a bug in either vagrant or vagrant-vbguest. In those places in which you describe a "hang", vagrant (and vagrant-vbguest) are either running some commands over ssh on the box or fiddling with virtual box tools to do networking tasks (mounting folder for example).
My bet would be some networking issue on your host or guest system. In most of my networking issue cases it has been some kind of DNS issue, where each request ran into a some kind of timeout. You would recognize those kind of error by the amount of time each "hang" takes (they would all be almost the same time - eg: 3 seconds).

But please, try to take this to either the Vagrant mailing list or Virtualbox forum. There are way more people available to help you.

**Comment by akaSStalkALEX** [comment]
https://github.com/mitchellh/vagrant/issues/6812
