### ISSUE TITLE
Vbox guest additions exit at the confirmation dialog

### ISSUE THREAD

**Issue by Petrox** [dotless-de/vagrant-vbguest#199]
I'm using a vagrant box with preinstalled (apt-get) virtualbox guest additions.

Of course the host machine is very unlikely to have the same version, so vagrant-vbguest should install the correct one, but fails at the confirmation dialog.

```
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
stdin: is not a tty
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
Installing Virtualbox Guest Additions 4.3.36 - guest version is 4.3.10
stdin: is not a tty
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.36 Guest Additions for Linux............
VirtualBox Guest Additions installer
You appear to have a version of the VBoxGuestAdditions software
on your system which was installed from a different source or using a
different type of installer.  If you installed it from a package from your
Linux distribution or if it is a default part of the system then we strongly
recommend that you cancel this installation and remove it properly before
installing this version.  If this is simply an older or a damaged
installation you may safely proceed.

Do you wish to continue anyway? [yes or no]

Cancelling installation.
An error occurred during installation of VirtualBox Guest Additions 4.3.36. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
stdin: is not a tty

```

As vbguest runs earlier than my provisioning script, this happens every time before I could remove the packages. Also it should be part of the automatic installation, or just force the install through.

**Comment by mente** [comment]
Double it

**Comment by Petrox** [comment]
Looks like, this happens, when the original vagrantbox is old, and the apt-get purge fails if no apt-get update was run before.

As I've found the ubuntu.rb does not have the apt-get update, while the debian.rb does have it, so it probably happens with ubuntu guests only.

**Comment by NickBelhomme** [comment]
+1

**Comment by Petrox** [comment]
Patch exists, and worksforme.

**Comment by mente** [comment]
@Petrox i have same issue but with Debian as guest machine. Can you make same patch for it as well?

**Comment by Petrox** [comment]
@mente I'm not a ruby developer, so my patch was just a trivial edit. Also as I see, the debian version works very different (why?), so it's probable, that you don't have the same problem.

Mine was that apt-get purge does not work if the apt cache is outdated, because the removal of some packages triggers installing some others in my vagrant box, and those are not found.

In the debian file I see, that if installation fails, the code handles that, and retries the installation after an apt-get update (which is nice), BUT does not seem to check whether the virtual machine already has some prepackaged guestadditions (maybe pure debian don't have those debs in the repo?).

Anyway, if you feel, you have the same bug, please attach the corresponding log, to let the developers handle it, or open a different issue.

Although as I see, there are old pending pullrequests so the devs are probably inactive. :(

**Comment by Petrox** [comment]
@fnordfish thanks for the fix.

 FYI as @mente has noted, the problem might exist in the debian installer too.
