### ISSUE TITLE
GuestAdditions seems to be installed (5.0.14) correctly, but not running.

### ISSUE THREAD

**Issue by JimGaylard** [dotless-de/vagrant-vbguest#202]
Every time I run `vagrant up|reload` I get the following error.

```
GuestAdditions seems to be installed (5.0.14) correctly, but not running.

stdin: is not a tty
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
bash: line 4: vboxadd: command not found

stdin: is not a tty
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

Restarting VM to apply changes...
```

If I restart as it says to do I get the same as above.

When the vm has started:

```
$> vagrant vbguest --status
GuestAdditions 5.0.14 running --- OK.
```

Any idea what's happening here?

Host: OS X 10.11.3
Guest: Ubuntu 15.04
Vagrant version: 1.8.1
Virtualbox version: 5.0.14

**Comment by atadams** [comment]
:+1:

**Comment by ChrisWiegman** [comment]
Seeing the same issue with the same specs as @atadams. The only thing I can add is my error message is slightly different some times (other times it is the same as reported):

`==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.0.14
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (5.0.14) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.0.14
Going on, assuming VBoxService is correct...`

**Comment by ChrisWiegman** [comment]
No change with the 5.0.16 update.

**Comment by HenrikBechmann** [comment]
@ChrisWiegman ditto

as before I add

      config.vbguest.auto_update = false  

to my Vagrantfile, but comment out whenever I upgrade VirtualBox, then uncomment between upgrades to avoid this annoying behaviour.

**Comment by HenrikBechmann** [comment]
also anyone can run

`vagrant vbguest`

and get 

`GuestAdditions 5.0.16 running --- OK.`

between Virtualbox updgrades.

Of course this seems to mean that vbguest contains the correct logic to check for the current version of GuestAdditions, but the check process during auto_update is faulty.

Not sure why it wouldn't get fixed. This problem has been around for a couple of years now...

**Comment by alejandrofcarrera** [comment]
The same here (Mac OS 10.11.3 - VBox 5.0.16)

Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 5.0.16
Going on, assuming VBoxService is correct...
GuestAdditions seems to be installed (5.0.16) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 5.0.16
Going on, assuming VBoxService is correct...
stdin: is not a tty
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
bash: line 3: vboxadd: command not found
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 5.0.16
Going on, assuming VBoxService is correct...
stdin: is not a tty

**Comment by mferrier** [comment]
:+1:

**Comment by HenrikBechmann** [comment]
@alejandrofcarrera I don't think it's actually installing an old version, just mis-reporting

after vagrant up, do `vagrant vbguest` to see

**Comment by alejandrofcarrera** [comment]
@HenrikBechmann Yes, you are right, it is not going to install that version.
BTW, i updated additions from 5.0.14 to 5.0.16 and it did not updated it, it reported that message.
My solution was to destroy the machine and re up to install 5.0.16 from beginning (bad move with each update) and after that i got the same message with the next "vagrant up".

Right now i have auto_update to false like you.

**Comment by danez** [comment]
same here

**Comment by ITler** [comment]
I'm experiencing same problem for quite a long time with different vagrant and vbox versions. For almost every `vagrant up`, I can see this behaviour. I think, it got worse after moving my boxes from SSD to HDD. It seems at least in my case it is just a matter of timing. SSH of the box gets available, but vbguest check for running virtualbox service happens to early while box is still booting.
Does this make sense?
If yes, it would maybe be convenient to introduce a customizable (via Vagrantfile) delay?

**Comment by richard-scott** [comment]
Is it safe to assume you all have the vagrant-vbguest plugin installed??
```
$ vagrant plugin list
vagrant-share (1.1.5, system)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.11.0) <---------------------- This one.
```
That is required for automatic updates of the guest OS services.

**Comment by HenrikBechmann** [comment]
Yup

On Wed, May 4, 2016 at 4:25 AM, Richard Scott <notifications@github.com>
wrote:

> Is it safe to assume you all have the vagrant-vbguest plugin installed??
>
> $ vagrant plugin list
> vagrant-share (1.1.5, system)
> vagrant-triggers (0.5.3)
> vagrant-vbguest (0.11.0) <---------------------- This one.
>
> That is required for automatic updates of the guest OS services.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dotless-de/vagrant-vbguest/issues/202#issuecomment-216782050>
>



-- 
internetcommons.ca

**Comment by awalls** [comment]
Having the same problem with this. Added 

```
if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
end
```

which at least suppresses the error.

**Comment by guusdk** [comment]
#191 appears to fix this error:
```
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
bash: line 4: vboxadd: command not found
```

I applied the change from that issue manually to this file, after which the error disappeared:
```
~/.vagrant.d/gems/gems/vagrant-vbguest-0.11.0/lib/vagrant-vbguest/installers/linux.rb
```

I'm pretty sure that modifying files manually like that will void any warranty.

**Comment by neilgee** [comment]
Seeing this in VB 5.1.2

```
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
[default] GuestAdditions 5.1.2 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
```

Result of `vbguest version`
```
neilg@[~/vdev]:(develop) vagrant vbguest
[default] GuestAdditions 5.1.2 running --- OK.
```

**Comment by n-rodriguez** [comment]
May be linked to https://github.com/dotless-de/vagrant-vbguest/issues/224#issuecomment-275181898

**Comment by hemangajmera** [comment]
I copied VBoxGuestAdditions.iso from VirtualBox installation directory to local directory and added below line in VagrantFile and it worked

config.vbguest.iso_path = "VBoxGuestAdditions.iso"

Not sure why this happens. But in case this helps

**Comment by hovissimo** [comment]
I had a whole lot of trouble with this issue before, but I've recently tried again and it "just works" now.

VirtualBox 5.1.18
Vagrant 1.9.3
Using `ubuntu/trusty64` dated version 20170313.0.7 on an Ubuntu 16.04 host.

I did get a "do not match" after initially provisioning the VM, but it appears that the vbguest plugin correctly installed the updated version automatically because I have received no further errors or problems.

**Comment by vanquang9387** [comment]
Same here. Mis-report during auto update:
```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.28
VBoxService inside the vm claims: 5.1.22
```

```
$ vagrant vbguest --status
[default] GuestAdditions 5.1.22 running --- OK.
```

**Comment by ruionwriting** [comment]
Same as @vanquang9387 on OSX.

**Comment by javinc** [comment]
after `vagrant up`

do `vagrant vbguest --do install`

then `vagrant reload`

to check `vagrant vbguest --status` should be ok

**Comment by Cyclonecode** [comment]
@javinc - When running `vagrant vbguest --do install` I get:

Cancelling installation.
An error occurred during installation of VirtualBox Guest Additions 5.1.24. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
vboxadd: unrecognized service
vboxadd-service: unrecognized service

**Comment by dmitrymar** [comment]
In my case after seemingly successfully installation of vbguest, the automatic update of the guest additions on vm box didn't work. So the way I fixed it is I ssh into the guest box which is an arch linux machine and upgraded all packages with ```pacman -Syu``` command.

**Comment by michael-schnell** [comment]
In my case this problem seems to be caused by a bug in VirtualBox. The problem was with `virtualbox-5.2_5.2.8-121009~Ubuntu~zesty_amd64.deb` and disappeared after switching to `virtualbox-5.2_5.2.12-122591~Ubuntu~zesty_amd64.deb`  - See [vagrant-packet-builder issue #9](https://github.com/fuinorg/vagrant-packet-builder/issues/9) for details.

**Comment by HammerTien** [comment]
I found something strange. I installed the Vagrant 2.2.2 and VirtualBox 6.0.0 in `D:\` in Win10 . I did `vagrant up` with the same box in disk `D:\` and `E:\` and the error came out in `E:\` but disappeared in `D:\`.
