### ISSUE TITLE
Mount ISO Image from CD Drive

### ISSUE THREAD

**Issue by richard-scott** [dotless-de/vagrant-vbguest#215]
Is there a way to get the required ISO contenst from the CD Drive attached to a VM?

I use this in my Vagrantfile:
```
vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "/usr/share/virtualbox/VBoxGuestAdditions.iso"]
```
And it would be great if vagrant-vbguest could use that for its source...
is that possible?

**Comment by fnordfish** [comment]
I can't think of an easy way how to do this right now. You probably can create an own Installer (or even monkey patch ) and overwrite `upload(iso_file)` to do nothing and `mount_iso(opts, &block)` to mount your cd/dvd device.

The reason why vbguest does not rely on the attached storage is, that it is (or at least was when writing this) very unlikely that a box has the iso file already linked as a storage device.

Having said that: I would be happy to merge a pull request which introduces this feature (preferably as a configuration switch on a per-machine basis).

**Comment by richard-scott** [comment]
ok, thanks for the info :-)
