### ISSUE TITLE
SLES11sp4: No provider of 'kernel-devel' found.

### ISSUE THREAD

**Issue by hesco** [dotless-de/vagrant-vbguest#216]
zypper se kernel shows I already have installed a package going by:  kernel-default-devel.  
Yet because kernel-devel is not found, things break down and my GuestAdditions are 
never reconciled between host and guest.  

Is there some way of instructing vagrant-vbguest that kernel-default-devel just might satisfy 
this requirement?  

Might this be a simple patch to the code?

**Comment by hesco** [comment]
Testing patch to:
lib/vagrant-vbguest/installers/opensuse.rb 

        packages = ['kernel-default-devel', 'gcc', 'make', 'tar']

and this seems to have worked.

**Comment by glookie1** [comment]
My workaround was to create a metapackage named kernel-devel that has a dependency to dernel-default-devel as suse renamed that package in SLES 11.4.
In SLES 12 they reverted the change back to kernel-devel.

**Comment by vpereira** [comment]
it is related with issue #219 

We need a SLES dedicated installer. openSUSE installer should work on opensuse.
