### ISSUE TITLE
Auto-update should be disabled by default?

### ISSUE THREAD

**Issue by tknerr** [dotless-de/vagrant-vbguest#22]
I'm sure there is a reason that auto-update is true by default.

My personal preference though would be that auto-update is disabled by default. 

Why? Because now that I have the vagrant-vbguest gem installed it is automatically turned on for all my Vagrantfiles, which I don't want for various reasons, e.g. increased startup time for when installing latest guest additions, maybe I don't need / want the latest guest additions, etc.

Still, I would love to be able to update the guest additions with a single entry in the Vagrantfile (running as middleware), or via a simple `vagrant vbguest` command. 

I want it as simple as it is with `vagrant-vbguest` now, but I want the choice when it happens - without having to modify all my Vagrantfiles.

Does that make sense? :-)

**Comment by discopatrick** [comment]
I'd like to give my +1 to this issue, as I'm finding I'm adding the following code block to every Vagrantfile where I don't want VBox Additions to update:

```
if Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.no_install = true
end
```

The conditional check is in case my team members don't have vagrant-vbguest installed.

I could set a global variable to overwrite the value, but this can't be checked into the repo, and it's nice to have all config stored in the repo (although, admittedly, it could be documented in the readme that this needs to be done manually).

I'd also like to suggest that the changing of default behaviour could happen on the next major version number. Backwards compatibility is only assumed between minor version numbers (where adhering to semantic versioning rules: http://semver.org/).
