### ISSUE TITLE
Don't auto update by default

### ISSUE THREAD

**Issue by carlosefr** [dotless-de/vagrant-vbguest#226]
The `vagrant-vbguest` plugin is very useful, but it's also a frequent source of problems with VMs that already include the guest tools (for an example, try to start vagrant's own development VM) because of its default-on behavior.

I believe `config.vbguest.auto_update` should default to `false` and be enabled explicitly on Vagrantfiles that wish to use it, or globally in the user's `vagrant.d/Vagrantfile`.

**Comment by fnordfish** [comment]
Sorry, not going to happen (see #22). You can disable `auto_update` in `vagrant.d/Vagrantfile` (see: https://github.com/dotless-de/vagrant-vbguest#global-configuration) pretty much like you suggested - just the other way round ;)
