### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by Asher256** [dotless-de/vagrant-vbguest#228]
Hi,

Suggestion: this is the Arch Linux path to the guest additions /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso 

If you want to add the Arch Linux support.

Asher256

**Comment by fnordfish** [comment]
Hi Asher256,
thanks, but this path in path is included for a while now. Do you use a particular old version of vagrant-vbguest, or is it simply not working for you?

**Comment by Asher256** [comment]
Hello fnordfish,

I upgraded vagrant-vbguest to 0.12.0 and it worked without 'config.vbguest.iso_path'.

Thank you!
