### ISSUE TITLE
it is always checking and installing vbguest

### ISSUE THREAD

**Issue by Raffaello** [dotless-de/vagrant-vbguest#239]
I have this config in the `Vagrantfile`:

```
  config.vbguest.no_install  = true if defined? config.vbguest
  config.vbguest.auto_update = false if defined? config.vbguest
  config.vbguest.no_remote   = true if defined? config.vbguest
```

but It does not care and install anyway. The only solution to do not install  `vbguest` is to remove the plug-in.

I do not want share directory in this vagrant file with VB Guest Add On but with NFS. 

I am force to remove the plugin due to the fact i do not want polluting my guest os kernel with VB.

Am I configuring wrong/ missing something or it is a bug?

EDIT:

the vagrant output after the package required to install vbguest is:

```
[...]
Complete!
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.1.10 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.10 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Building Guest Additions kernel modules.
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.

```

**Comment by richard-scott** [comment]
It is better to run the VB Addons on a Guest VM as it helps the Host VirtualBox know about the internals of the VM. That aside... What Host OS do you run?  What Guest OS are you installing in VirtualBox?

Also, what versions of:

- VirtualBox
- Vagrant
- vbguest plugin 

Do you run?

**Comment by fnordfish** [comment]
Just a wild guess (b/c I haven't seen it that way yet) instead of using `defined?` try to wrap your config like this:

```ruby
if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install  = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote   = true
end
```

**Comment by Raffaello** [comment]
@richard-scott  I am running Fedora 24 as Host, the guest is a CentOS/7 Box.

**Comment by Raffaello** [comment]
@richard-scott,

host Fedora 25
guest Centos/7

vagrant 1.8.5
Virtual Box 5.1

**Comment by Raffaello** [comment]
@fnordfish actually that solve the issue.
missed the `Vagrant.has_plugin` variable.

Thanks for help.

I can close the ticket
