### ISSUE TITLE
Failed to mount shared folder in RedHat Guest

### ISSUE THREAD

**Issue by nullkarma** [dotless-de/vagrant-vbguest#241]
VirtualBox: 5.1.10
vagrant: 1.9.1
vagrant-vbguest: 0.13.0
Box:
  - centos/7: 1610.01

Tested on:
  - MacOS: 10.11.6
  - Ubuntu 16.04.1 LTS

Working on:
  - bento/centos-7.2: 2.3.1

**Error Message**

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 srv_repos /srv/repos

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**However, on Guest host:**

*during vagrant up*

```
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
[...]
boxadd.sh: Building Guest Additions kernel modules.
Failed to set up service vboxadd, please check the log file
/var/log/VBoxGuestAdditions.log for details.
```

**/var/log/VBoxGuestAdditions.log**

```
vboxadd.sh: failed: Look at /var/log/vboxadd-install.log to find out what went wrong.
vboxadd.sh: failed: Please check that you have gcc, make, the header files for your Linux kernel and possibly perl installed..
```

**/var/log/vboxadd-install.log**

```
/tmp/vbox.0/Makefile.include.header:97: *** Error: unable to find the sources of your current Linux kernel. Specify KERN_DIR=<directory> and run Make again.  Stop.
Creating user for the Guest Additions.
Creating udev rule for the Guest Additions kernel module.
```

Seems to be a box thing. Feel free to close this issue, if it doesn't affect vbguest.

**Comment by alexkillen** [comment]
I have the same issue (host: Windows 10, box: centos/7 1610.01).  Work around for a single VM would be to ssh into the VM and run "yum update", then do a "vagrant reload". 

For multiple VMs, it's quicker to disable the synced folder, set vbguest.auto_update to false and to replace the provisioner used with a basic one that simply does a "yum update -y". Do a "vagrant up", then re-enable the synced folder, vbguest, and your actual provisioner, and then "vagrant reload".

Disable synced folder:
`config.vm.synced_folder ".", "/vagrant", disabled: true`

Disable vbguest auto update:
`config.vbguest.auto_update = false`

**Comment by alexkillen** [comment]
Also, just to confirm, this is an issue with the box. See following comment:
[https://seven.centos.org/2016/11/updated-centos-vagrant-images-available-v1610-01/#comment-89524](url)

**Comment by orsenthil** [comment]
I observed this issue on Mac, with this plugin!

Uninstalling the plugin, helped with proceed.

**Comment by oly-l-yates** [comment]
I had this issue with the centos/7 box the solution posted here worked for me https://github.com/dotless-de/vagrant-vbguest/issues/240

**Comment by rawroland** [comment]
This is a similar, if not the same problem mentioned in the issue #240

**Comment by Pupp3tm4st3r** [comment]
Hi,

i had this issue, too. I tried a vagrant up with an outdated OS version (an olrder CentOS 6.7 box). I found out, that the problem was, that the installed kernel was older than the downloaded/updated (by vbguest plugin) kernel headers. After updating the kernel (or yum update...) it worked. So it seems, that the problem is, that for some versions, the plugin loads the latest kernel-headers but the kernel stays on the old version. This will break the install/update process for the virtual box guest additions.

**Comment by chekunkov** [comment]
Issue already discussed [here](https://github.com/mitchellh/vagrant/issues/8502) and [here](https://www.virtualbox.org/ticket/16670#comment:4). One of the workarounds worked for me:

```
# run inside guest and then `vagrant reload`
sudo ln -sf /opt/VBoxGuestAdditions-5.1.20/lib/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf
```
