### ISSUE TITLE
Guest do not sync time after resume

### ISSUE THREAD

**Issue by pollydrag** [dotless-de/vagrant-vbguest#247]
After suspend and resume guest do not sync system time with host.

Minimal steps to reproduce:
```
vagrant init puppetlabs/debian-7.8-64-nocm
vagrant up --provider virtualbox
vagrant suspend
... wait ...
vagrant resume
```

**Comment by fnordfish** [comment]
Sorry, although this might be an issue with the guest additions, it does not look like an issue with this plugin. Please check with the Vagrant or VirtualBox project.
