### ISSUE TITLE
Rsync default

### ISSUE THREAD

**Issue by luka-zitnik** [dotless-de/vagrant-vbguest#257]
Hi,

I've got this:

```
[default] GuestAdditions 5.1.22 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Rsyncing folder:
```

Is it familiar to you?

ps virtualbox sync type works if explicit in config.

**Comment by fnordfish** [comment]
Looks like your base box's Vagrantfile has a explicit rsync config in it. Check out https://www.vagrantup.com/docs/vagrantfile/ "Load Order and Merging"

**Comment by luka-zitnik** [comment]
You are right. Thank you Robert!
