### ISSUE TITLE
Add support for OpenIndiana

### ISSUE THREAD

**Issue by xen0l** [dotless-de/vagrant-vbguest#261]
In OpenIndiana (open source Solarish operating system), we are using vagrant for development purposes. It would be nice if this great plugin supported autoupdating guest additions. I will see what I can come up with in the upcoming days.

**Comment by fnordfish** [comment]
Thanks! May I suggest you look into realeasing as a separate gem/plugin. For an example, check out https://github.com/fnordfish/vagrant-vbguest-centos
