### ISSUE TITLE
error occurred while installing vagrant-vbgueset

### ISSUE THREAD

**Issue by bencasper** [dotless-de/vagrant-vbguest#262]
An error occurred while installing unf_ext (0.0.7.4), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.4'` succeeds before bundling.

resolved by 

yum install gcc-c++  libstdc++-devel

**Comment by fnordfish** [comment]
Weird, `unf_ext` is a dependency of vagrant, not vagrant-vbguest. Also, vagrant-vbguest does not specify a dependency on vagrant (aside from the development in the Gemfile, which vagrant should ignore when installing)
