### ISSUE TITLE
An error occurred during installation of VirtualBox Guest Additions 5.1.26 on ARTACK/debian-jessie

### ISSUE THREAD

**Issue by GabLeRoux** [dotless-de/vagrant-vbguest#267]
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ARTACK/debian-jessie' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (5.1.26) and guest (5.1.22) do not match.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.16.0-4-amd64 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.1.26 - guest version is 5.1.22
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.26 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Removing installed version 5.1.22 of VirtualBox Guest Additions...
This system appears to have a version of the VirtualBox Guest Additions
already installed.  If it is part of the operating system and kept up-to-date,
there is most likely no need to replace it.  If it is not up-to-date, you
should get a notification when you start the system.  If you wish to replace
it with this version, please do not continue with this installation now, but
instead remove the current version first, following the instructions for the
operating system.

If your system simply has the remains of a version of the Additions you could
not remove you should probably continue now, and these will be removed during
installation.

Do you wish to continue? [yes or no]

Cancelling installation.
An error occurred during installation of VirtualBox Guest Additions 5.1.26. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Failed to start vboxadd.service: Unit vboxadd.service failed to load: No such file or directory.
Failed to start vboxadd-service.service: Unit vboxadd-service.service failed to load: No such file or directory.
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.4.11 project.dev
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> default: Mounting NFS shared folders...
==> default: Mounting shared folders...
    default: /vagrant => /path/to/project/shared_folder
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: unknown filesystem type 'vboxsf'
```

> Installing Virtualbox Guest Additions 5.1.26 - guest version is 5.1.22
> [...]
> Cancelling installation.
> An error occurred during installation of VirtualBox Guest Additions 5.1.26. Some functionality may not work as intended.

This error occured after upgrading Virtualbox on MacOS to `Version 5.1.26 r117224 (Qt5.6.2)` with virtualbox

## Versions

```
$ vboxmanage --version
5.1.26r117224
```

```
$ vagrant --version
Vagrant 1.9.7
```

```
$ vagrant plugin list
hostmanager (1.2.2)
  - Version Constraint: > 0
vagrant-hostmanager (1.8.7)
  - Version Constraint: > 0
vagrant-hostsupdater (1.0.2)
  - Version Constraint: > 0
vagrant-rekey-ssh (0.1.9)
  - Version Constraint: > 0
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
vagrant-vbguest (0.14.2)
  - Version Constraint: > 0
```

```
$ vagrant box list -i
ARTACK/debian-jessie  (virtualbox, 8.1.0)
```

```
MacOS Sierra 10.12.6
```

Vagrant box debian version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.1 (jessie)
Release:	8.1
Codename:	jessie
```

```
$ uname -a
Linux project 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

## Workaround

```bash
$ vagrant destroy
$ vagrant up
```

This is not a very good workaround, but at least, installing from scratch does work.

**Comment by dendrochronology** [comment]
I ran into the same issue.  To avoid rebuilding, I did this on the host to copy the local additions ISO into the guest:

`vagrant vbguest sco_dev_box --do install --no-cleanup`

...then SSH'd into the guest and manually ran the installer:

`sudo /mnt/VBoxLinuxAdditions.run`

...which allowed me to agree to the installer prompt, so it would stop dying.

After restarting, things seem fine.

Did the additions installer script not have an interactive prompt before? A quick check of the googles didn't bring up any obvious silent/quiet flags.

**Comment by alexkart** [comment]
Any other solutions for this issue?

`vagrant vbguest sco_dev_box --do install --no-cleanup`
doesn't work on windows

**Comment by alexkart** [comment]
In case someone else also needs a solution for this issue with Windows host and Ubuntu guest

This article helped me http://www.techrepublic.com/article/how-to-install-virtualbox-guest-additions-on-a-gui-less-ubuntu-server-host/

Few notes:
- if you don't have an optical drive in your VM, first open VirtualBox GUI and add an optical drive to the VM
- you may not have /media/cdrom directory in the VM, so create it before mounting cdrom

**Comment by richard-scott** [comment]
I've just had to do the same (mount the ISO on a newly added CD Drive in the VM) on a Ubuntu Host, with a Debian Guest. This is with VirtualBox 5.1.28. Manually installing the additions worked, the vbguest v0.14.2 plugin borked for some reason (nothing obvious in the logs).

**Comment by greg-hayes** [comment]
Got this working (unattended) by upgrading vagrant from 1.9.x to 2.0.0
Also:
vbguest: 0.14.2, VirtualBox: 5.1.28
box: centos/7 - 1708.1

**Comment by richard-scott** [comment]
Debian is obviously different to Centos then as with Vagrant 2.0.0 and VB 5.1.28 it doesn't work for me automatically. I have to do a manual install.

**Comment by GabLeRoux** [comment]
I had the issue again today and I confirm [dendrochronology (Aaron)'s instructions](https://github.com/dotless-de/vagrant-vbguest/issues/267#issuecomment-322220198) work. Just replace `sco_dev_box` with your box name (usually `default` by default, or you can leave it blank).

```bash
vagrant vbguest --do install --no-cleanup
vagrant ssh
yes | sudo /mnt/VBoxLinuxAdditions.run
```

❤️

**Comment by pvalena** [comment]
The guide above works for me on `Win 7` with `Vagrant 2.0.1` and `vagrant-vbguest (0.15.0)`. But that may be because running it via [Cygwin](https://www.cygwin.com/).

All in one:
```bash
vagrant up ; vagrant vbguest --do install --no-cleanup ; vagrant ssh -c 'yes | sudo /mnt/VBoxLinuxAdditions.run'
```

**Comment by doveraudio** [comment]
I'm not sure if this is related, but i'm using CentOS 7.4 from Bento in my box. I use this plugin, and it SEEMS like it installs the guest additions every time i boot it.

**Comment by mityukov** [comment]
@GabLeRoux followed your instructions (for installing vba from within running vm) and the installation, finally gone through without errors!

However, when I do `vagrant up` — still get "VBox Additions are installed but not running" and no shared folders attached. It's on Win 10.

Have anyone faced issue like this?

P.S.: the box is laravel/homestead version: 0.6.0 if that matters. I'm running the same box on my Mac OS without any issues and I was able to run it on one Win 10 machine previously. So, I'm not sure it's related to the box anyhow.
