### ISSUE TITLE
Protocol "C" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by worp1900** [dotless-de/vagrant-vbguest#272]
Trying this config:

    config.vbguest.iso_path = File.expand_path("VBoxGuestAdditions_5.1.0_RC1.iso", __FILE__)

Gives me

    [myVm] GuestAdditions versions on your host (5.1.26) and guest (5.1.0) do not match.
    Loaded plugins: fastestmirror, priorities
    Loading mirror speeds from cached hostfile
     * base: centos.bio.lmu.de
     * epel: mirror.i3d.net
     * extras: mirror.cuegee.de
     * updates: mirror.eu.oneandone.net
    523 packages excluded due to repository priority protections
    Package kernel-devel-3.10.0-693.2.2.el7.x86_64 already installed and latest version
    Package gcc-4.8.5-16.el7.x86_64 already installed and latest version
    Package binutils-2.25.1-32.base.el7_4.1.x86_64 already installed and latest version
    Package 1:make-3.82-23.el7.x86_64 already installed and latest version
    Package 4:perl-5.16.3-292.el7.x86_64 already installed and latest version
    Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
    Nothing to do
    Downloading VirtualBox Guest Additions ISO from C:/my/path/to/vm/dev/Vagrantfile/VBoxGuestAdditions_5.1.0_RC1.iso

    ==> myVm: Checking for guest additions in VM...
    An error occurred while downloading the remote file. The error
    message, if any, is reproduced below. Please fix this error and try
    again.

    Protocol "C" not supported or disabled in libcurl

Host:
Windows 10

Guest:

    $ cat /etc/centos-release
    CentOS Linux release 7.4.1708 (Core)

I am assuming vbguest tries to access the iso-path as a web-url and finds "C:" instead of "http:"? Should be windows specific.

Providing the iso-path as a cli argument, using vbguest as a command, it works:
`$ vagrant vbguest --iso VBoxGuestAdditions_5.1.0_RC1.iso --do install`

**Comment by fnordfish** [comment]
Can you try please try: `config.vbguest.iso_path = "VBoxGuestAdditions_5.1.0_RC1.iso"` instead of giving the absolute path (guessing from your comment that command line argument works). The command line argument does basically the same as `config.vbguest.iso_path`.

Internally, vbguest relies on Vagrant's `Downloader` class. So, if it'a a bug, it's probably a bug in there.

**Comment by worp1900** [comment]
Will try that tomorrow. Thx for the hint.

**Comment by worp1900** [comment]
Works like a charm. Shot you a pull request if you want to update it in the readme: #273
