### ISSUE TITLE
Bug: Solaris 11.3 box - Can't determine version

### ISSUE THREAD

**Issue by danowar2k** [dotless-de/vagrant-vbguest#275]
Hi,

I'm using the Solaris box from https://app.vagrantup.com/heavybeans/boxes/solaris11-small-server
I can't update the GuestAdditions because:
"Sorry, don't know how to check guest version of Virtualbox Guest Additions on this platform. Stopping installation."
I don't speak Ruby, but if you could point me to the place where the version detection is done, I could probably suggest the command or whatever that one could use to check the version on Solaris...

**Comment by fnordfish** [comment]
Hi @danowar2k 
thanks for your interest in bringing Solaris support to this project. But version detection is just the tip of the iceberg. Up next would be detecting the state of the current additions installation, optionally in-place-rebuilt them, installing build dependencies, mounting the iso and running the installer script.

However, my time maintaining this project is rather limited and I tend to not add the burden of supporting additional platforms. However, vbguest is extendable through vagrant plugins (rubygems). 
If you are interested to get your hands dirty with some ruby, I'm willing to help you out - with the ruby part that is.
Here are two samples of how such a project would look like:
- https://github.com/dotless-de/vagrant-vbguest/tree/master/testdrive/vagrant-vbguest-unikorn
- https://github.com/fnordfish/vagrant-vbguest-centos

Closing as "won't fix" for the moment, but please comment below if you'd like to (or know someone who does) create an extension.
