### ISSUE TITLE
vagrant up on ubuntu cloud images fails when using vbguest plugin

### ISSUE THREAD

**Issue by jarl-dk** [dotless-de/vagrant-vbguest#278]
To reproduce:

```
$ vagrant --version
Vagrant 2.0.1
$ vagrant plugin list
vagrant-share (1.1.9, system)
vagrant-vbguest (0.15.0)
$ vagrant init ubuntu/artful64
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
$ vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/artful64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/artful64' is up to date...
==> default: Setting the name of the VM: vagrant-bug_default_1515002901534_82359
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.1.28
VBoxService inside the vm claims: 5.1.30
Going on, assuming VBoxService is correct...
[default] GuestAdditions seems to be installed (5.1.30) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.1.28
VBoxService inside the vm claims: 5.1.30
Going on, assuming VBoxService is correct...
Failed to start vboxadd.service: Unit vboxadd.service not found.
Failed to start vboxadd-service.service: Unit vboxadd-service.service not found.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.1.28
VBoxService inside the vm claims: 5.1.30
Going on, assuming VBoxService is correct...
bash: line 4: setup: command not found
==> default: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 4: setup: command not found

```

**Comment by nhojpatrick** [comment]
This was previous being discussed at https://bugs.launchpad.net/cloud-images/+bug/1740178

On Mac the the following ubuntu images work;
ubuntu/trusty64
ubuntu/xenial64
ubuntu/zesty64

But fails with;
ubuntu/artful64

If I do;
$ vagrant up
... fails as original post
$ vagrant plugin uninstall vagrant-vbguest
$ vagrant destroy
$ vagrant up
... works
$ cat Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	# fix "stdin: is not a tty"
	config.vm.provision "fix-no-tty", type: "shell" do |s|
		s.privileged = false
		s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
	end

	config.vm.provider :virtualbox do |vb|
		vb.gui = false
		vb.customize ["modifyvm", :id, "--memory", "384"]
	end

	config.vm.box = "ubuntu/artful64"

end
$

**Comment by jarl-dk** [comment]
Another workaround is to run
```
vagrant vbguest --do install
vagrant up
```
When it fails

**Comment by PatchRanger** [comment]
Taking into account @jarl-dk 's https://github.com/dotless-de/vagrant-vbguest/issues/278#issuecomment-358023589 together with https://github.com/dotless-de/vagrant-vbguest#config-options , I've composed even better workaround:

Add this to `Vagrantfile`:
```
config.vbguest.installer_arguments = ['--nox11', '-- --do']
```
\- and it will stop failing! Doubled double-slash is required.
Cheers)

**Comment by richard-scott** [comment]
Try updating to the latest image. I've just used it with the above [Vagrantfile ](https://github.com/dotless-de/vagrant-vbguest/issues/278#issuecomment-355122425)and its fine.
https://app.vagrantup.com/ubuntu/boxes/artful64

My setup has the following plugins:
```
vagrant plugin list
vagrant-host-shell (0.0.4)
vagrant-hostmanager (1.8.8)
vagrant-rancher (1.1.4)
vagrant-reload (0.0.1)
vagrant-share (1.1.9)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.15.1)

```

**Comment by RogerWeihrauch** [comment]
Hello Richard
Thank you for your hints. I will try them. Nevertheless; I am using the dcos-vagrant cluster on Debian 8.10 host system (more for stability reasons), not as baremetal nor as onpremise nor as 'aws cloud'; so 'completely' virtualized, since I am in case studies on DC/OS. Do you think this could cause 'my' problems with VboxGuestAdditions' installation during 'vagrant up'? Since VBGuestAdditions will not install completely, automatically and with no errors, DC/OS may/will be my second choice.
Thank you for your response,
Roger

**Comment by giltroymeren** [comment]
@jarl-dk, @RogerWeihrauch and @PatchRanger's workarounds didn't work for me unfortunately.

Environment:
- Windows 10
- VBox 5.2.12
- Vagrant 2.1.1
- CentOS 7

**Comment by anfe0690** [comment]
None of the workarounds worked for me.

My environment is:

- Linux Mint 18.2 KDE
- Vagrant 2.1.1
- vagrant-vbguest 0.15.1
- VirtualBox 5.2.12 r122591
- config.vm.box = "centos/7"

**Comment by richard-scott** [comment]
I've just tried "vagraint init centos/7; vagrant up" with the following:

- Ubuntu 18.04
- Vagrant 2.1.2
- vagrant-vbguest 0.15.2
- VirtualBox 5.2.16 r123759

And it works nicely for me:
```
==> default: Machine booted and ready!
[default] GuestAdditions 5.2.16 running --- OK.
```

**Comment by jan2ary** [comment]
Still reproduces for me:

- Ubuntu 18.10 (beta)
- guest vm is generic/ubuntu1810
- Vagrant 2.1.5
- vagrant-vbguest 0.15.2
- virtualbox 5.2.18-dfsg-2

```
==> default: Machine booted and ready!
[default] GuestAdditions seems to be installed (5.2.18) correctly, but not running.
bash: line 4: setup: command not found
==> default: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 4: setup: command not found


```

**Comment by fnordfish** [comment]
I'm going out on a limb here, but I suppose it's a script run by the VirtualBox Guest Additions installer, not vbguets. (the only place when vbguest runs something like `setup` is, when it tries to run the re-install routine of an existing GA installation, and that's a singe command).

Can you try and run in debug mode (https://www.vagrantup.com/docs/other/debugging.html) to see which command gets send to the VM right before that error occurs.

**Comment by renoirb** [comment]
I can confirm seeing similar problem.  I will report and confirm is symptom and proposed solution still work.
I wish Vagrant had a documented way to case-switch conditional block for detecting on which OS the current vagrant is running.

**Comment by gadkrumholz** [comment]
This is happening again, using VBox 6.0.6 that came out recently... the issue is with an error in the install script of the VBox Guest additions ISO that gets shipped with VBox... 

Going back to VBox 5.2.28 works as a workaround.

**Comment by yihjie** [comment]
Here is my result 

`[docker-host] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
bash: line 4: setup: command not found
==> docker-host: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 4: setup: command not found`

**Comment by markuszeller** [comment]
> 
> 
> A workaround is to run
> 
> ```
> vagrant vbguest --do install
> vagrant up
> ```
> 
> When it fails

Great tip! Thank you!
Before `vagrant up` I had to do a `vagrant halt`.

**Comment by danepowell** [comment]
Can we reopen this? Or do we need a new issue?

I'm also encountering this with Virtualbox 6.0.6. Downgrading to 6.0.4 seemed to fix it for now.

**Comment by gabewong** [comment]
> Can we reopen this? Or do we need a new issue?
> 
> I'm also encountering this with Virtualbox 6.0.6. Downgrading to 6.0.4 seemed to fix it for now.

This appears to be an issue with Virtualbox. I was able to resolve the issue by downgrading to 6.0.4 per recommendation by Dane with the following commands: 
```
$ brew cask uninstall virtualbox
$ brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/d7f8219fa51f7c96a17c346acfab547a6af7f956/Casks/virtualbox.rb
```

**Comment by danepowell** [comment]
It sounds like an issue should be opened with Virtualbox, is anyone familiar enough with this problem / the Virtualbox project to do that?

**Comment by gabewong** [comment]
I've created a ticket with Virtualbox - https://www.virtualbox.org/ticket/18598

**Comment by Dave3o3** [comment]
Related or maybe the same issue? https://github.com/dotless-de/vagrant-vbguest/issues/333

**Comment by roc1** [comment]
run 
vagrant plugin install vagrant-vbguest
boxes works just fine.

**Comment by Kiarashz** [comment]
VBGuest Addition plugin works with VB 6.0.6 when creating VM but fails on subsequent call to 'vagrant up' when trying to configure VB Guest Addition that seems not to be running.

**Comment by Kocal** [comment]
VB 6.0.6 is kinda broken, try with 6.0.4

**Comment by jubalfh** [comment]
This seems to be caused by check for vboxsf (similar what you can see in the vboxadd*) scripts, see relevant part of the logs + some context:

```sh
DEBUG guest: Trying: redhat
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /etc/redhat-release (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
 INFO guest: Detected: redhat!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: test -f /etc/centos-release (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "d340c071-593a-4880-bd64-2e80211168d4", "--machinereadable"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="mgt"
[stdout output removed for clarity]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: VBoxService --version (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0

> DEBUG ssh: Re-using SSH connection.
>  INFO ssh: Execute: lsmod | grep vboxsf (sudo=true)
> DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
> DEBUG ssh: Exit status: 1

DEBUG vbguest-machine: Current states for VM 'mgt' are : guest_version=6.0.6 : host_version=6.0.6 : running=false
 INFO interface: warn: [mgt] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
[mgt] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
```

Forcing the module to be loaded at the boot seems to work fine as a workaround:
```ruby
  config.vm.provision "shell", run: "always", inline: <<-WORKAROUND
    modprobe vboxsf || true
  WORKAROUND
```

**Comment by karthikbaikati** [comment]
This is still happening. Is there a permanent fix?

**Comment by danepowell** [comment]
This is still an issue for me in Virtualbox 6.0.8. Keep in mind that the issue only seems to appear the second time you start the box (after the additions have already been installed), so you might be fooled into thinking it's solved if you just spin up a new box once on the new version of vbox.

**Comment by fidanf** [comment]
> 
> 
> This is still an issue for me in Virtualbox 6.0.8. Keep in mind that the issue only seems to appear the second time you start the box (after the additions have already been installed), so you might be fooled into thinking it's solved if you just spin up a new box once on the new version of vbox.

Seconded. I had to rollback to 6.0.4 because of this.

**Comment by Fenn-CS** [comment]
In case you are using vagrant, from ubuntu's apt repository, uninstall it and step away from the scenario immediately!
`sudo apt-get purge vagrant`
`sudo apt-get clean`
`sudo apt-get autoremove`

 **Now download vagrant's `.deb` by Hashicop from https://www.vagrantup.com/downloads.html install and the error would be gone *IN CASE you installed vagrant from apt***

**Comment by pbj23000** [comment]
Host: Windows 10 (1809)
Virtual Box: Version 6.0.8 r130520 (Qt5.6.2)
Vagrant 2.2.4
VBGuest: vagrant-vbguest (0.17.2, global)
Guest: bento/centos-7.6    (virtualbox, 201812.27.0)

I solved the above with: 
```echo vboxsf > /etc/modules-load.d/vboxsf.conf```

I'm not sure if it needs added to the plugin, or if it's missing from the VBoxGuestAdditions-6.0.8 installer.

**Comment by openface** [comment]
Running VirtualBox 6.0.8 here.   Updating vagrant-vbguest to version 0.18.0 fixed this issue for me.

**Comment by deejay2** [comment]
I confirm, updating to vagrant-vbguest 0.18.0 fixes the issue on Vbox 6.0.8.
Just run once in the project:
`vagrant plugin update vagrant-vbguest` 
You should see it updated to 0.18.0 and then you'll not see that error back! :) Thank you @openface !

**Comment by Urielable** [comment]
> I confirm, updating to vagrant-vbguest 0.18.0 fixes the issue on Vbox 6.0.8.
> Just run once in the project:
> `vagrant plugin update vagrant-vbguest`
> You should see it updated to 0.18.0 and then you'll not see that error back! :) Thank you @openface !

This works for me, thanks!

**Comment by aleevas** [comment]
> I confirm, updating to vagrant-vbguest 0.18.0 fixes the issue on Vbox 6.0.8.
> Just run once in the project:
> `vagrant plugin update vagrant-vbguest`
> You should see it updated to 0.18.0 and then you'll not see that error back! :) Thank you @openface !

Works for me too! Thanks!

**Comment by brianbirir** [comment]
> Running VirtualBox 6.0.8 here. Updating vagrant-vbguest to version 0.18.0 fixed this issue for me.

This also works for me. Thank you.

**Comment by rubo77** [comment]
I use virtualbox-guest-dkms 6.1.6-dfsg-1 in a Ubuntu focal64 image and on the Host: virtualbox                                                  6.0.14-dfsg-1

But I have the same problem here now
