### ISSUE TITLE
Update fails during provisioning

### ISSUE THREAD

**Issue by danepowell** [dotless-de/vagrant-vbguest#281]
My environment:

```
Vagrant 2.0.1
VirtualBox 5.2.4r119785
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/dane/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
vagrant-vbguest 0.15.0
```

My OS:
 - **macOS** (High Sierra)

Summary:
I have vagrant-vbguest installed to automatically update guest additions. I'm also using Drupal VM.

Whenever I run `vagrant up` on a new VM, using either beet/box or geerlingguy/ubuntu1604 as a base box, vagrant-vbguest attempts to update the guest additions but errors out.

You can see my provisioning log here:
[provision.txt](https://github.com/dotless-de/vagrant-vbguest/files/1613704/provision.txt)

And the guest additions update log here:
[vboxadd-setup.log](https://github.com/dotless-de/vagrant-vbguest/files/1613705/vboxadd-setup.log)

Snip from the provision log with the relevant error:
```
[aep] GuestAdditions versions on your host (5.2.4) and guest (5.1.28) do not match.
Reading package lists...
Building dependency tree...
dkms is already the newest version (2.2.0.3-2ubuntu11.5).
linux-headers-4.4.0-87-generic is already the newest version (4.4.0-87.110).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.2.4 - guest version is 5.1.28
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.4 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 5.1.28 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: modprobe vboxsf failed
An error occurred during installation of VirtualBox Guest Additions 5.2.4. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details
```

As you can see there's some sort of error about missing headers (from the vboxadd log):
```
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
```

**Comment by angoras** [comment]
+1

**Comment by iamamused** [comment]
+1

**Comment by ansiblejunky** [comment]
I just recently installed this plugin thinking it would really help with maintaining the latest guest additions on my machines, but I have only hit problems every time when I do `vagrant up` and it attempts to provision my system by updating the machine's guest additions version. I have used bento boxes from Vagrant Cloud and have not done any changes to them. Either its missing dependencies or there are other nasty errors that I do not wish to explore. 

So I agree with this issue logged, and additionally I am asking for some more testing on the plugin because perhaps I am missing something but it has hurt more than helped me with my machines.

Here is my latest error that I hit.
```
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
```

**Comment by richard-scott** [comment]
There is a feature with the 5.1.x VB Guest modules where they don't unload from running memory when the services are stopped. This is what causes this error. The 5.2 drivers update nicely. This isn't an issue with the plugin, but the drivers.

You'll need to remove the old 5.1 drivers manually for now if you want an automatic update/install in the future with 5.2.x

**Comment by ansiblejunky** [comment]
Removing the 5.1 drivers, meaning the virtualbox drivers? or virtualbox guest drivers? In that case, do you mean the full guest additions installation on the guest machine?

**Comment by ansiblejunky** [comment]
The uninstall worked, however when I startup the machine `vagrant up` the plugin failed to install the guest additions.  

```
==> ol6-latest: Machine booted and ready!
[ol6-latest] GuestAdditions seems to be installed (5.2.8) correctly, but not running.
start: missing job name
Try `start --help' for more information.
start: missing job name
Try `start --help' for more information.
bash: line 4: setup: command not found
==> ol6-latest: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 4: setup: command not found
```

**Comment by ansiblejunky** [comment]
I figured out the issue with `line 137: /dev/tty: No such device or address`.  From manually trying to install the Guest Additions ISO file from within the machine it still failed. 

After some investigation (error messages don't help at all) it seems the install script requires both `which` and `tar` packages to be installed and my machine didn't have these. It seems quite a bare-bones machine from Oracle. 

After adding these packages, the Guest Additions installs correctly and the vbguest plugin shows it is running now. 

I highly recommend that vbguest installs both `which` and `tar` when I run the command. It already installs a bunch of other required packages.
```
vagrant vbguest [vmname] --do install
```
