### ISSUE TITLE
Installing failed

### ISSUE THREAD

**Issue by Michel73** [dotless-de/vagrant-vbguest#283]
Host: Windows7, 10
Guest: Ubuntu 16.04
Virtualbox: 5.2.6
vagant: 2.0.1
vagrant-vbguest: 0.15.1
```
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: modprobe vboxsf failed
An error occurred during installation of VirtualBox Guest Additions 5.2.6. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> MI1701: Checking for guest additions in VM...
    MI1701: The guest additions on this VM do not match the installed version of
    MI1701: VirtualBox! In most cases this is fine, but in rare cases it can
    MI1701: prevent things such as shared folders from working properly. If you see
    MI1701: shared folder errors, please make sure the guest additions within the
    MI1701: virtual machine match the version of VirtualBox you have installed on
    MI1701: your host and reload your VM.
    MI1701:
    MI1701: Guest Additions Version: 5.1.14
    MI1701: VirtualBox Version: 5.2
==> MI1701: Setting hostname...
==> MI1701: Mounting shared folders...
    MI1701: /vagrant => D:/git/new_vagrant/ubuntu-intellij
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

The installation with the same base-box  `tknerr/ubuntu1604-desktop` was successful with the following versions:
Virtualbox: 5.1.30
vagant: 1.9.1
vagrant-vbguest: 0.13.0

**Comment by xalopp** [comment]
This is an issue present in VirtualBox 5.2.x 😢  5.1.x isn't affected.
The workaround for the guest additions mentioned at [VirtualBox issue #17486](https://www.virtualbox.org/ticket/17486#comment:1) doesn't work for me (SLES11SP4) 😞 , so I'm using VirtualBox 5.1.32 for now.

**Comment by atorstling** [comment]
If I run the command in the guest, I get `[  486.027705] sf_read_super_aux err=-71` in dmesg. Running an `strace -f` on the mount command gives `[pid  1712] mount("vagrant", "/vagrant", "vboxsf", MS_NODEV, "") = -1 EPROTO (Protocol error)
[pid  1712] getcwd("/opt/VBoxGuestAdditions-5.2.6", 4096) = 30
[pid  1712] mount("vagrant", "/vagrant", "vboxsf", MS_NODEV, "") = -1 EPROTO (Protocol error)
[pid  1712] write(2, "/sbin/mount.vboxsf: mounting fai"..., 50/sbin/mount.vboxsf: mounting failed with the error) = 50`.

Another curiosity is that there is a broken symlink in /usr/lib:
`vagrant@vagrant-ubuntu-trusty-64:/opt/VBoxGuestAdditions-5.2.6$ ll /usr/lib/VBoxGuestAdditions
lrwxrwxrwx 1 root root 52 Feb 12 12:37 /usr/lib/VBoxGuestAdditions -> /opt/VBoxGuestAdditions-5.2.6/lib/VBoxGuestAdditions`

**Comment by PatchRanger** [comment]
Possible workaround: https://github.com/dotless-de/vagrant-vbguest/issues/278#issuecomment-381318862 .

**Comment by Michel73** [comment]
Doesn't worked for me! Same failure!

**Comment by giltroymeren** [comment]
@PatchRanger's workaround didn't work for me unfortunately.

Environment:
- Windows 10
- VBox 5.2.12
- Vagrant 2.1.1
- CentOS 7

**Comment by giltroymeren** [comment]
@xalopp what version of Vagrant do you use with your VBox 5.1.32?

**Comment by xalopp** [comment]
@giltroymeren Guest OS: SLES11SP4, VirtualBox 5.1.32, Vagrant 2.1.1, vbguest 0.15.1
The issue here is on VirtualBox side.

Today I experienced with  Centos/7 (1803.1), VirtualBox 5.2.12,  Vagrant 2.1.1, vbguest 0.15.1 an issue similar to  #240 . If the current kernel-devel from the yum repo doesn't match the  kernel version run in the box (`uname -r`) vbguest will fail to build :-(

**Comment by anfe0690** [comment]
I'm facing the same issue.

My environment is:
- Linux Mint 18.2 KDE
- Vagrant 2.1.1
- vagrant-vbguest 0.15.1
- VirtualBox 5.2.12 r122591
- config.vm.box = "centos/7"

**Comment by atorstling** [comment]
I noticed the following: If you use ubuntu LTS and configure it to use upstart, it still leaves some remnants of systemd in the config. The vbguest installer subsequently thinks systemd is being used and configures it as a systemd service. The consequence is that it will never be started...

**Comment by dohpaz42** [comment]
Host: macOS High Sierra (10.13.5 (17F77))
Guest: CentosBox/Centos7-v7.3-Minimal (17.08.09)
vagrant: 2.1.2
vagrant-vbguest: 0.15.2
VirtualBox: 5.2.16
GuestAdditions: 5.2.16

Error:
```
...
VirtualBox Guest Additions installer
Removing installed version 5.1.26 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting.
*** VirtualBox Guest Additions: modprobe vboxsf failed ***
An error occurred during installation of VirtualBox Guest Additions 5.2.16. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start  vboxadd.service
Redirecting to /bin/systemctl start  vboxadd-service.service
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> jenkins: Checking for guest additions in VM...
    jenkins: The guest additions on this VM do not match the installed version of
    jenkins: VirtualBox! In most cases this is fine, but in rare cases it can
    jenkins: prevent things such as shared folders from working properly. If you see
    jenkins: shared folder errors, please make sure the guest additions within the
    jenkins: virtual machine match the version of VirtualBox you have installed on
    jenkins: your host and reload your VM.
    jenkins: 
    jenkins: Guest Additions Version: 5.1.26
    jenkins: VirtualBox Version: 5.2
==> jenkins: Setting hostname...
==> jenkins: Configuring and enabling network interfaces...
    jenkins: SSH address: 127.0.0.1:2222
    jenkins: SSH username: vagrant
    jenkins: SSH auth method: private key
==> jenkins: Mounting shared folders...
    jenkins: /vagrant => /Users/kstanl27/Development/deployable
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

It appears that even though the `vboxsf` module could not be inserted, the default behavior from `auto_reboot` is not actually reload/restarting the VM as one would expect. I even went so far as to add it to my Vagrantfile just in case.

However, manually running `vagrant reload --provision` from the command line does the trick.
