### ISSUE TITLE
nfs not works and still don't know how to handle the error for guest additions

### ISSUE THREAD

**Issue by sidealice** [dotless-de/vagrant-vbguest#289]
vagrant plugin list
vagrant-share (1.1.9, system)
vagrant-vbguest (0.15.1)

vagrant -v
Vagrant 2.0.1

How to upgrade the guest additions? should it be upgraded automatically.

Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.10
VBoxService inside the vm claims: 5.2.8
Going on, assuming VBoxService is correct...
[default] GuestAdditions 5.2.8 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.10
VBoxService inside the vm claims: 5.2.8
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.2
==> default: Configuring and enabling network interfaces...
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.

**Comment by richard-scott** [comment]
That doesn't look like a vbguest plugin error.... but a base image error.
What do you have "config.vm.box"set to?
Are you remembering to setup a dedicated NFS network interface in your Vagrantfile?

**Comment by sidealice** [comment]
Vagrant.configure(2) do |config|
  config.vm.box = "magneto19"
  config.vm.network "forwarded_port", guest: 1088, host: 1088
  config.vm.network "forwarded_port", guest: 1089, host: 1089
  config.ssh.forward_agent = true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "/vagrants", "/vagrants",create: true, owner:"www-data",group:"www-data"
  config.vm.synced_folder "/git-data", "/git-data",type:"nfs"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
end

thanks for your reply, above is my config. It works for years but recently it can't work.

**Comment by richard-scott** [comment]
I believe you need to set a static IP for NFS to work correctly. This is because on the server side the VM's IP is used to restrict access.

```
config.vm.network "private_network", ip: "192.168.50.4"
```

Obviously use an IP in the range your private network is using.

**Comment by sidealice** [comment]
thanks after change the ip it solved.

i don't know the reason why it suddenly broken before but it works again now, thanks!
