### ISSUE TITLE
bento/ubuntu-16.04: automatic update of guest additions fails, manual update works just fine

### ISSUE THREAD

**Issue by ltalirz** [dotless-de/vagrant-vbguest#294]
I'm running vagrant 2.0.3 & Virtualbox 5.2.8 and want to update the vbox guest additions in the latest [bento-ubuntu16.04](https://app.vagrantup.com/bento/boxes/ubuntu-16.04/versions/201803.24.0) box, which comes with the vbox guest additions 5.2.6 preinstalled.

When using the vbguest plugin, I get the well-known error message
```
An error occurred during installation of VirtualBox Guest Additions 5.2.8. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
```
Basic functionality like clipboard sharing between host and VM does not work (even after rebooting the VM).

Then, I run `vagrant vbguest  --do install --no-cleanup` (receive the error message again), ssh into the VM, run `sudo /mnt/VBoxLinuxAdditions.run` => No error message (see below).
```
$ sudo /mnt/VBoxLinuxAdditions.run
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.8 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 5.2.8 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting.
You may need to restart the Window System (or just restart the guest system)
to enable the Guest Additions.
```
I reboot the VM and clipboard sharing works just fine.

Any ideas what may be going on here?

P.S. Here the full output of `vagrant vbguest  --do install --no-cleanup` when run on a VM that has not been touched by vbguest before:
```
$ vagrant vbguest  --do install --no-cleanup
[default] GuestAdditions versions on your host (5.2.8) and guest (5.2.6) do not match.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version (2.2.0.3-2ubuntu11.5).
The following NEW packages will be installed:
  linux-headers-4.4.0-87 linux-headers-4.4.0-87-generic
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.7 MB of archives.
After this operation, 78.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 linux-headers-4.4.0-87 all 4.4.0-87.110 [9,892 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 linux-headers-4.4.0-87-generic amd64 4.4.0-87.110 [785 kB]
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Fetched 10.7 MB in 1s (7,119 kB/s)
Selecting previously unselected package linux-headers-4.4.0-87.
(Reading database ... 152543 files and directories currently installed.)
Preparing to unpack .../linux-headers-4.4.0-87_4.4.0-87.110_all.deb ...
Unpacking linux-headers-4.4.0-87 (4.4.0-87.110) ...
Selecting previously unselected package linux-headers-4.4.0-87-generic.
Preparing to unpack .../linux-headers-4.4.0-87-generic_4.4.0-87.110_amd64.deb ...
Unpacking linux-headers-4.4.0-87-generic (4.4.0-87.110) ...
Setting up linux-headers-4.4.0-87 (4.4.0-87.110) ...
Setting up linux-headers-4.4.0-87-generic (4.4.0-87.110) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.4.0-87-generic /boot/vmlinuz-4.4.0-87-generic
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Forcing installation of Virtualbox Guest Additions 5.2.8 - guest version is 5.2.6
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.8 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 5.2.6 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting.
An error occurred during installation of VirtualBox Guest Additions 5.2.8. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
```

**Comment by ltalirz** [comment]
The problem arose from installing the guest additions on a headless box, and installing ubuntu desktop afterwards.
If the guest additions are (re-)installed after installing the desktop, and the VM is restarted, the guest additions work as expected.

Still, the error message `An error occurred during installation of VirtualBox Guest Additions 5.2.8...` remains - the `/mnt/VBoxLinuxAdditions.run` script indeed exits with status code 2. I wonder why...

**Comment by yogeek** [comment]
@ltalirz I use Vagrant with ubuntu/bionic source box which is headless and ansible-local provisioner and have the same problem : vbguest installs guest additions before my ansible installation of ubuntu desktop  and i do not have bidirectinnal copy/paste working if I do not re-install guest addition manually at the end.
Do you have a solution to avoid adding an ansible task to instal guest addition again please ?

**Comment by ltalirz** [comment]
> Do you have a solution to avoid adding an ansible task to instal guest addition again please ?

I don't, sorry.
I would have eventually created such a task but, unexpectedly,  the problem recently seems to have gone away (with Ubuntu). 
At least when using
 *`vagrant 2.1.5`
 * `vbguest 0.16.0`
 * `bento/ubuntu-18.04`, version `201808.24.0`
things like the bidirectional clipboard were working when installing ubuntu desktop *after* the vbguest additions.

**Comment by yogeek** [comment]
I have the error with the following versions :

- vagrant 2.2.2
- vbguest 0.17.1
- ubuntu/bionic64

I install xdesktop with Ansible and things like bidirectionnal clipboard are enabled in virtualbox but not working until I reinstalled guest additions manually at the end of the ansible provisioning.
