### ISSUE TITLE
This system is currently not set up to build kernel modules

### ISSUE THREAD

**Issue by reypm** [dotless-de/vagrant-vbguest#301]
I am trying to get a CentOS6 box up & running but for some reason the "VirtualBox Guest Additions" fails to install. This is all I have read & tried:

- https://www.if-not-true-then-false.com/2010/install-virtualbox-guest-additions-on-fedora-centos-red-hat-rhel/
- https://superuser.com/questions/1268741/virtualbox-ubuntu-guest-additions-not-installing-modprobe-vboxsf-failed
 - https://github.com/dotless-de/vagrant-vbguest/issues/264
 - https://github.com/dotless-de/vagrant-vbguest/issues/300
 - https://github.com/dotless-de/vagrant-vbguest/issues/161
 - https://github.com/dotless-de/vagrant-vbguest/issues/266
 - https://github.com/dotless-de/vagrant-vbguest/issues/298
 - https://github.com/dotless-de/vagrant-vbguest/issues/270
 - https://github.com/chef/bento/issues/1041
 - https://stackoverflow.com/questions/49369065/rhel-this-system-is-currently-not-set-up-to-build-kernel-modules
 - https://superuser.com/questions/412527/modprobe-vboxguest-failed

This is how my `Vagrantfile` looks like:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder "../../applications", "/var/www/html"
  config.vbguest.iso_path = "./VBoxGuestAdditions_5.2.14.iso"

  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.name = "appserver"
   end
end
```

This is the message I am getting while trying to install the VBoxGuestAdditions:

> Copy iso file ./VBoxGuestAdditions_5.2.14.iso into the box /tmp/VBoxGuestAdditions.iso
> Mounting Virtualbox Guest Additions ISO to: /mnt
> Installing Virtualbox Guest Additions 5.2.14 - guest version is unknown
> Verifying archive integrity... All good.
> Uncompressing VirtualBox 5.2.14 Guest Additions for Linux........
> VirtualBox Guest Additions installer
> Copying additional installer modules ...
> Installing additional modules ...
> VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.
> This system is currently not set up to build kernel modules.
> Please install the Linux kernel "header" files matching the current kernel
> for adding new hardware support to the system.
> The distribution packages containing the headers are probably:
>     kernel-devel kernel-devel-2.6.32-696.28.1.el6.x86_64
> VirtualBox Guest Additions: Starting.
> VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.
> This system is currently not set up to build kernel modules.
> Please install the Linux kernel "header" files matching the current kernel
> for adding new hardware support to the system.
> The distribution packages containing the headers are probably:
>     kernel-devel kernel-devel-2.6.32-696.28.1.el6.x86_64
> An error occurred during installation of VirtualBox Guest Additions 5.2.14. Some functionality may not work as intended.
> In most cases it is OK that the "Window System drivers" installation failed.
> VirtualBox Guest Additions: Starting.
> VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.
> egrep: Unmatched ) or \)
> This system is currently not set up to build kernel modules.
> Please install the Linux kernel "header" files matching the current kernel
> for adding new hardware support to the system.
> The distribution packages containing the headers are probably:
>     kernel-devel kernel-devel-2.6.32-696.28.1.el6.x86_64
> modprobe vboxguest failed
> The log file /var/log/vboxadd-setup.log may contain further information.

And here is the list of dependencies installed:

```
Dependencies Resolved

================================================================================
 Package             Arch        Version                     Repository    Size
================================================================================
Installing:
 gcc                 x86_64      4.4.7-23.el6                base          10 M
 kernel-devel        x86_64      2.6.32-754.2.1.el6          updates       11 M
Updating:
 binutils            x86_64      2.20.51.0.2-5.48.el6        base         2.8 M
Installing for dependencies:
 cloog-ppl           x86_64      0.15.7-1.2.el6              base          93 k
 cpp                 x86_64      4.4.7-23.el6                base         3.7 M
 glibc-devel         x86_64      2.12-1.212.el6              base         991 k
 glibc-headers       x86_64      2.12-1.212.el6              base         620 k
 kernel-headers      x86_64      2.6.32-754.2.1.el6          updates      4.5 M
 libgomp             x86_64      4.4.7-23.el6                base         135 k
 mpfr                x86_64      2.4.1-6.el6                 base         157 k
 ppl                 x86_64      0.10.2-11.el6               base         1.3 M
Updating for dependencies:
 glibc               x86_64      2.12-1.212.el6              base         3.8 M
 glibc-common        x86_64      2.12-1.212.el6              base          14 M
 libgcc              x86_64      4.4.7-23.el6                base         104 k

Transaction Summary
================================================================================
Install      10 Package(s)
Upgrade       4 Package(s)
```

I am seeing both `kernel-devel` and `kernel-headers` why VirtualBox Guest Additions is failing to install? What I am missing here?

Currently I am using:

- Vagrant 2.1.2
- Version 5.2.14 r123301

**Comment by DanielWeinerBT** [comment]
I ran into a similar issue recently.  My solution was to create a custom installer.

My Vagrantfile:

```
class CustomInstaller < VagrantVbguest::Installers::RedHat
  def install(opts=nil, &block)
    communicate.sudo('yum -y update kernel', opts, &block)
    super
  end
end


Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-6.7"
    config.vbguest.installer = CustomInstaller
    ...
end
```

This updates the kernel on the guest machine before installing other dependencies.
