### ISSUE TITLE
vagrant 2.1.2 cannot install vagrant-vbguest correctly

### ISSUE THREAD

**Issue by tyy0402** [dotless-de/vagrant-vbguest#309]
@fnordfish 

I uninstalled vagrant 2.1.4. Since I cannot remove it totally, I just deleted all the documents which contain "vagrant".
After installed vagrant 2.1.2, run `vagrant plugin install vagrant-vbguest vagrant-triggers`
it shows 
```
Plugin vagrant-vbguest is not installed. Install it with:
vagrant plugin install vagrant-vbguest vagrant-triggers
```

How can I fix it? Thanks soooooooo much!

**Comment by tyy0402** [comment]
BTW, I found that vagrant has 2.1.5.
I did't try whether the new version is worked

**Comment by fnordfish** [comment]
my guess is, you are running it from within a Vagrant project. That is some directory containing a `Vagrantfile` and in that `Vagrantfile` there's some code checking for the existence of the plugin.

try runnig outside of a vagrant project.

BTW: Yes, you should upgrade to 2.1.5

**Comment by tyy0402** [comment]
You are right! Thanks!!!!!!!!
