### ISSUE TITLE
An error occurred during installation of VirtualBox Guest Additions

### ISSUE THREAD

**Issue by RogerWeihrauch** [dotless-de/vagrant-vbguest#316]
Hello Community
Since #267 was closed; I want to (re-) open a -nother/-new one on the same issue but wit another relase version. I am using actually VBox 5.2.22 and its VboxGuestAdditions in the same version.
I already tried the follwoing hint from #267:
vagrant up ; vagrant vbguest --do install --no-cleanup ; vagrant ssh -c 'yes | sudo /mnt/VBoxLinuxAdditions.run'
but ran in tot the same issue as desrcribed there.
Following the messages on monitor:
--- snip ---
.
.
.
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: modprobe vboxsf failed
An error occurred during installation of VirtualBox Guest Additions 5.2.22. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start  vboxadd.service
Redirecting to /bin/systemctl start  vboxadd-service.service
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
VM must be created before running this command. Run `vagrant up` first.
 INFO dcos-vagrant: Validating Plugins...
 INFO dcos-vagrant: Validating User Config...
 INFO dcos-vagrant: Validating Installer Checksum...
 INFO dcos-vagrant: Using DC/OS Installer: installers/dcos/dcos_generate_config-1.11.0.sh
 INFO dcos-vagrant: Using DC/OS Config: etc/config-1.11.0.yaml
 INFO dcos-vagrant: Validating Machine Config...
 INFO dcos-vagrant: Validating Command...
 INFO dcos-vagrant: Configuring VirtualBox Host-Only Network...
This command requires a specific VM name to target in a multi-VM environment.
vagrant@StretcH:~/dcos-vagrant$
-- snap ---
So, how do I use the solution of #267 in a multi-VM environment with `vagrant up` to get more that one VM started AND updated with VboxGuestAdditions module, esp. the very necessary vboxsf module?
BTW, the mentioned VM is already up and runnning done by vagrant up.
Thank you all for your help. 

Kind regards,
Roger

**Comment by xserrat** [comment]
I have the same issue... The only way to fix it is:
1. `vagrant plugin uninstall vagrant-vbguest`
2. `vagrant destroy -f`
3. `vagrant up`
4. `vagrant plugin install vagrant-vbguest`

**Comment by xacaxulu** [comment]
+1

**Comment by mmguide2003** [comment]
This happens every time I halt vagrant with VirtualBox 6.1.4.  Very annoying.

**Comment by ashishmohite** [comment]
`vagrant reload` works every time i get this error

**Comment by lehien** [comment]
No luck with me. In my case, I had to specify version of vbguest, the latest 0.28 seems buggy and I use 0.21, now it worked!
`vagrant plugin uninstall vagrant-vbguest`

`vagrant plugin install vagrant-vbguest --plugin-version 0.21`

**Comment by vinieq** [comment]
you can use the newest plugin. Just make sure you this this thing:
https://github.com/dotless-de/vagrant-vbguest

`Vagrant.configure("2") do |config|
  config.vm.define "my_cent_os_box" do |c|
    c.box = "centos/8"
    c.vbguest.installer_options = { allow_kernel_upgrade: true }
  end
end`

**Comment by jakec-dev** [comment]
> you can use the newest plugin. Just make sure you this this thing:
> https://github.com/dotless-de/vagrant-vbguest
> 
> ```
> Vagrant.configure("2") do |config|
>   config.vm.define "my_cent_os_box" do |c|
>     c.box = "centos/8"
>     c.vbguest.installer_options = { allow_kernel_upgrade: true }
>   end
> end
> ```

That doesn't work unfortunately. Issue here: https://github.com/dotless-de/vagrant-vbguest/issues/316
