### ISSUE TITLE
kernel headers not installed properly on  centos/7 (virtualbox, 1811.02)

### ISSUE THREAD

**Issue by lambliesdown** [dotless-de/vagrant-vbguest#317]
After upgrading to 0.17.0 the vbguest plugin doesn't install the kernel headers kernel-devel.x86_64 0:3.10.0-957.1.3.el7  any more. I'm seeing that it's trying to install them but the are missing afterward. I reverted back to 0.16.0 and things worked fine.
Running the latest centos/7 box 1811.02 on VirtualBox 5.2.22 r126460 and vagrant 2.2.1

**Comment by savugin** [comment]
I had same issue with vbguest 0.17.0. So downgraded to vbguest 0.16.0 and it worked fine.
Running the latest centos/6 box on VirtualBox 5.2.22 and vagrant 2.2.2

**Comment by fnordfish** [comment]
Interesting. 0.17 brought an own centos installer which now takes precedence over the old redhat one.

Another option to use the redhat installer is to explicitly specify it in the Vagrantfile like this: `config.vbguest.installer = VagrantVbguest::Installers::RedHat`

Anyways, could you please provide some logs which show which packages, repos and exact centos-reases are being used.

**Comment by lambliesdown** [comment]
Attaching log files for vagrant. 
vagrant.log is the plain log, vagrant.debug.log output with debug level (a bit verbose)
vagrant version : 2.2.2
vagrant box : centos/7 (virtualbox, 1811.02)
Virtual Box 5.2.22 r126460
vagrant host OS : Linux centos7 3.10.0-957.1.3.el7.x86_64
guest OS : Linux centos7 3.10.0-957.1.3.el7.x86_64
guest repos : see attached repos.txt
[repos.txt](https://github.com/dotless-de/vagrant-vbguest/files/2690728/repos.txt)
[vagrant.debug.log](https://github.com/dotless-de/vagrant-vbguest/files/2690730/vagrant.debug.log)
[vagrant.log](https://github.com/dotless-de/vagrant-vbguest/files/2690731/vagrant.log)

**Comment by fnordfish** [comment]
Please check the just released v0.17.1
