### ISSUE TITLE
Adding SUSE 15 support

### ISSUE THREAD

**Issue by Fdall** [dotless-de/vagrant-vbguest#323]
Since SUSE Linux Enterprise Server 15 is now available.
In the SUSE installer, the dependencies are installed following the version given in the os-release file, but
stop to 13.
Modifying  in  [vagrant-vbguest/lib/vagrant-vbguest/installers/suse.rb](https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/suse.rb)

`when 12.0..13.0` to `when 12.0..15.0`

should be enough

**Comment by fnordfish** [comment]
Thanks! fixed in 913ce15f5bd3c3c82794af8641a6d01623a63c04 (not yet released)

**Comment by Fdall** [comment]
Great! That was quick!

**Comment by fnordfish** [comment]
easy enough update ;)
