### ISSUE TITLE
CentOS installer doesn't support kernel-lt/kernel-ml

### ISSUE THREAD

**Issue by spencerhakim** [dotless-de/vagrant-vbguest#325]
As mentioned in #320, the current implementation of the CentOS installer doesn't support the use of [`kernel-lt`](http://elrepo.org/tiki/kernel-lt) or [`kernel-ml`](http://elrepo.org/tiki/kernel-ml) from the Community Enterprise Linux Repo (ELRepo), as it assumes the guest is running the standard `kernel` package. These kernels also have their own matching support packages (`kernel-lt-{devel,doc,headers,tools}` and `kernel-ml-{devel,doc,headers,tools}`). To install these packages, the `elrepo-kernel` yum repo must be enabled.

An important note: older versions of these packages are **NOT** left available for download. So if the guest isn't running the most recent version of their kernel, something like ``yum install -y kernel-lt-devel-`uname -r` `` will fail.

**Comment by Roguelazer** [comment]
Yeah, is there any way to downgrade? 0.17.2 totally broken my company's processes (which rely on kernel-ml-*)

**Comment by fnordfish** [comment]
You don’t need to downgrade. Just put the “installer” config in your Vagrantfile set to the RedHat installer class.
