### ISSUE TITLE
Is it possible to enable/disable plugin per VM in case of multiple VMs

### ISSUE THREAD

**Issue by cstamas** [dotless-de/vagrant-vbguest#328]
In my scenario using 8 centos7 boxes (no vbguest present), I need vboxfs in two boxes only, while not in the rest. Still, the plugin is ON or OFF, so I need to wait for ALL boxes to have them built....

Or do I miss something?

**Comment by fnordfish** [comment]
Yes, you can just put the `vbguest.auto_update = false` config (or any of the [config options](https://github.com/dotless-de/vagrant-vbguest#config-options)) into your box's config block. EG:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web_config|
    web_config.vm.box = "apache"
    web_config.vbguest.auto_update = true
  end

  config.vm.define "db" do |db_config|
    db_config.vm.box = "mysql"
    db_config.vbguest.auto_update = false
  end
end
```

**Comment by cstamas** [comment]
Thanks for help, works like expected!
