### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [dotless-de/vagrant-vbguest#331]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by fnordfish** [comment]
There is none. I’ve simply found none which would allow the workflow. To install VirtualBox inside a probably virtualized environment. Also on different host OSs windows, Mac, ...

**Comment by gustavosizilio** [comment]
I see. I am studying the CI adoption and that kind of production environment is indeed a problem for CI adopters. 

I am closing this issue but will let you know if found some similar project using CI services.

**Comment by dcermak** [comment]
You can use Jenkins to run jobs on bare metal (and thus on any platform that you have access to), but this means that you have to self host & administer the Jenkins server and the Jenkins runners.
