### ISSUE TITLE
Update micromachine to version 3.0.0

### ISSUE THREAD

**Issue by dcermak** [dotless-de/vagrant-vbguest#336]
vagrant-vbguest depends on micromachine 2.x, however version 3.0.0 of this gem is available (https://github.com/soveran/micromachine/releases). Would you consider upgrading the version requirement of micromachine to `~> 3.0.0`?

**Comment by fnordfish** [comment]
Right now I have no plans of upgrading.  
Is there any particular reason for updating, like an incompatibility with another plugin?

--  
Robert Schulze

**Comment by dcermak** [comment]
It would make it a lot easier for me to package vagrant-vbguest for openSUSE Tumbleweed, as micromachine 2.0.0 is very old and it looks like it is not going to be accepted as a package, thereby making vagrant-vbguest miss a dependency.

**Comment by fnordfish** [comment]
will be updated with v0.19.0 see #341

**Comment by dcermak** [comment]
Thank you! And thanks @johanneskastl for #341.
