### ISSUE TITLE
FRE: Option to setup apt proxy to be used prior installing guest additions

### ISSUE THREAD

**Issue by MarcinOrlowski** [dotless-de/vagrant-vbguest#342]
I'd love to be able to specify APT proxy (or plant a file in `/etc/apt/apt.conf.d`) to be used by the plugin. I do have it set up by my provisioning scripts, yet on fresh guest, vbguest plugin kicks in before provisioner even had a chance to run and in my case it then ends up fetching packages from remote repos instead of use local APT proxy. I do currently break the process, setup proxy by hand and reload guest and trigger provisioning by hand but that's far from handy in longer run when I do have multiple guests to provision. Or is there any other way for me to run anything once box is set up but before your plugin starts?

**Comment by fnordfish** [comment]
You'd probably inherit the Installer class and overwrite it's `install` method to setup your apt config first. (See the example in  https://github.com/dotless-de/vagrant-vbguest#advanced-usage but as a base class you'd use `VagrantVbguest::Installers::Debian`)

I realize, that this is not really convenient as it requires to write quite some ruby code. A trigger or callback based mechanism would be much nicer.

**Comment by htjain** [comment]
Any solution for this ?
