### ISSUE TITLE
GuestAdditions seems to be installed (6.0.10) correctly, but not running.  (works with v0.17.2)

### ISSUE THREAD

**Issue by Morac2** [dotless-de/vagrant-vbguest#347]
When I upgraded from Vagrant 2.2.4 to 2.2.5 (Windows), I started getting a message that GuestAdditions was installed but not running.  This happens all the time even if I run the "vagrant vbguest --status <box>" command.

![image](https://user-images.githubusercontent.com/1596194/62153796-6131ad80-b2d3-11e9-80b4-1f4816d4c65f.png)

If I log into the actual virtual machine I can see that the guest additions are running.

![image](https://user-images.githubusercontent.com/1596194/62153910-9dfda480-b2d3-11e9-9a41-1249f2b020c9.png)

I was running an older version of VirtualBox, so I updated to the latest (6.0.10) which triggered vbguest-additions to install that guest addition version, but it still complains it's not running when bring up the VM or simply checking with the --status.

![image](https://user-images.githubusercontent.com/1596194/62154296-693e1d00-b2d4-11e9-8c39-d0ffb408e61b.png)

When  I tried digging into the vagrant-vbguest code, I noticed that during the Vagrant upgrade, it appears that vagrant-vbguest also updated.  The prior version I had installed (0.15.2) was in a gems 2.4.4 folder so I decided to try reverting to that version, along with micromachine 2.0.0.  After I did so everthing started working again, so something broke somewhere between 0.15.2 and 0.19.

![image](https://user-images.githubusercontent.com/1596194/62155279-6b08e000-b2d6-11e9-8361-cde5513d0df8.png)

Host: Windows 7 64
VM: Centos 6.5
Vagrant 2.2.5
VirtualBox 6.0.10
vagrant-vbguest 0.19.0

**Comment by Morac2** [comment]
I decided to go back and try older version of vagrant-vbguest and the last version that worked correctly was 0.17.2.  0.18.0 and 0.19.0 both report that GuestAdditions isn't running when it is.

**Comment by Morac2** [comment]
I dug into #334 and it looks like the code used to grep /proc/modules doesn't work in CentOS 6.5.

![image](https://user-images.githubusercontent.com/1596194/62156131-61807780-b2d8-11e9-8377-9eac30720be7.png)

The test command for vboxsf.ko does work, but not the grep.

**Comment by ciarancourtney** [comment]
This is still an issue as of v0.20.0 for CentOS 6, I'm using the below shell snippet to patch it for the time being:

```sh
    find ~/.vagrant.d/ -wholename "**/lib/vagrant-vbguest/installers/linux.rb" | while read file_path; do
        sed -i 's!grep.*/proc/modules!grep -q "^vboxguest" /proc/modules!' $file_path
    done
```

Note I'm just plonking `-q "^vboxguest"` between any instance of `grep` and `/proc/modules` in `linux.rb`, I'm not even going to try reasoning what the existing regex is looking for. FYI snippet is inherently idempotent.

**Comment by Morac2** [comment]
I simply changed the `grep -qE "^vboxguest\s.+\s\([^\s]*O[^\s]*\)$" /proc/modules` to `grep -qE "^vboxguest\s.+\s" /proc/modules`, removing the check for the `(*O*)` string.  I'm not sure why the current check is even looking for that.

**Comment by Nevermore-dh** [comment]
https://github.com/dotless-de/vagrant-vbguest/issues/333
