### ISSUE TITLE
Oracle Linux: No match for argument: kernel-uek-devel

### ISSUE THREAD

**Issue by chbi** [dotless-de/vagrant-vbguest#357]
Hi,

I use OracleLinux 8 image. vb-guests tries to install the package

    kernel-uek-devel-4.18.0-147.el8.x86_64

That results in the following error (copies from `vagrant up`):

    Error: Unable to find a match: kernel-uek-devel-4.18.0-147.el8.x86_64
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    yum install -y kernel-uek-devel-`uname -r` gcc make perl bzip2

    Stdout from the command:

    Last metadata expiration check: 0:02:04 ago on Wed 20 Nov 2019 07:26:15 AM UTC.
    No match for argument: kernel-uek-devel-4.18.0-147.el8.x86_64

I am not sure why, but there is no package kernel-uek-devel in Oracle Linux 8 image

     config.vm.box = "generic/oracle8"

probably vb-guests should not only check which distro in this case but also which version of Oracle Linux.

Kind regards,
Christian

**Comment by fnordfish** [comment]
fix released in 0.22.0
