### ISSUE TITLE
Guest installation fails on CentOS 8

### ISSUE THREAD

**Issue by sdchapman** [dotless-de/vagrant-vbguest#359]
Vagrant 2.2.6
Virtualbox 6.0.14

Using the centos/8 box, guest installation consistently fails. From the error log:

```Building the main Guest Additions 6.0.14 module for kernel 4.18.0-80.el8.x86_64.
Error building the module.  Build output follows.
make V=1 CONFIG_MODULE_SIG= -C /lib/modules/4.18.0-80.el8.x86_64/build M=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 -j2 modules
make[1]: warning: -jN forced in submake: disabling jobserver mode.
Makefile:958: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.
make: *** [/tmp/vbox.0/Makefile-footer.gmk:111: vboxguest] Error 2
Could not find the X.Org or XFree86 Window System, skipping.
modprobe vboxguest failed
```

If I SSH in and `yum install elfutils-libelf-devel` and reload, the additions then install fine and everything proceeds as normal, so I think that is the only missing package. It's present in CentOS6 and 7 repos as well so (hopefully) no harm in having the centos installer always install it.

**Comment by lucc** [comment]
I suspect that we need to add the item `'elfutils-libelf-devel'` to the list in https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/centos.rb#L67 iff `release_version == 8`.

But I don't know ruby so I can not realy open the PR :(

**Comment by sdchapman** [comment]
I think the package needs to go in centos.rb *and* redhat.rb (as per that other closed PR mentioned above, I missed that). I've tested it locally, probably no need for a version check as it doesn't break installation on CentOS 6 and 7.
