### ISSUE TITLE
vbguest is failing on centos/8 because of missing dependency

### ISSUE THREAD

**Issue by vonBork** [dotless-de/vagrant-vbguest#361]
Hi everybody,
I ran in an vbguest issue on centos 8 and Virtualbox 6.014. elfutils-libelf-devel wasn't installed. Coud anybody add it to the dependency list? I don't know where to do this.

`Building the main Guest Additions 6.0.14 module for kernel 4.18.0-80.el8.x86_64.                                                                      Error building the module.  Build output follows.                                                                                                     make V=1 CONFIG_MODULE_SIG= -C /lib/modules/4.18.0-80.el8.x86_64/build M=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 -j2 modules                                  make[1]: warning: -jN forced in submake: disabling jobserver mode.                                                                                    Makefile:958: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.  make: *** [/tmp/vbox.0/Makefile-footer.gmk:111: vboxguest] Error 2                                                                                    Could not find the X.Org or XFree86 Window System, skipping.                                                                                          modprobe vboxguest failed`

In case anybody wants to know, where I found the log, it's at /var/log/vboxadd-setup.log.

Vagrant: 2.2.6
Virtualbox: 6.0.14
Vagrant-vbguest: 0.21.0

**Comment by vonBork** [comment]
A workaround is to vagrant ssh, install the package by yourself and run vagrant vbguest. After that you might want to run vagrant up --provision to install what failed in the previous run.

**Comment by fnordfish** [comment]
This should be addressed in #360 - release coming soon

**Comment by vonBork** [comment]
Perfect and sorry I didn't check the pull requests. 🙈
