### ISSUE TITLE
How to install vagrant-vbguest plugin without Internet?

### ISSUE THREAD

**Issue by sssignals** [dotless-de/vagrant-vbguest#369]
Hi All

I would like to know how to install vagrant-vbguest offline without Internet? Thanks a lot in advance.
Vagrant 2.2.7
VBoxManage: 6.1.4r136177

**Comment by fnordfish** [comment]
You'll need an internet connection to download vagrant-vbguest an least once:
You need to install vbguests dependencies first.

```console
$ gem fetch micromachine -v ">= 2, < 4"
Fetching micromachine-3.0.0.gem
Downloaded micromachine-3.0.0
$ gem fetch vagrant-vbguest
Fetching vagrant-vbguest-0.23.0.gem
Downloaded vagrant-vbguest-0.23.0
$ vagrant plugin install ./micromachine-3.0.0.gem ./vagrant-vbguest-0.23.0.gem
Installing the './micromachine-3.0.0.gem' plugin. This can take a few minutes...
Installed the plugin 'micromachine (3.0.0)'!
Installing the './vagrant-vbguest-0.23.0.gem' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.23.0)'!
```

The `gem fetch` commands need internet to download the "gem files", once you have those, you can put them anywhere and use `vagrant plugin install` on them.

**Comment by sssignals** [comment]
Thanks fnordfish! 

I followed the  2 commands to download micromachine-3.0.0.gem and vagrant-vbguest-0.23.0.gem
1) gem fetch micromachine
2) gem fetch vagrant-vbguest

then 
3) vagrant plugin install ./micromachine-3.0.0.gem ./vagrant-vbguest-0.23.0.gem
got the error "Vagrant failed to load a configured plugin source... no such name (https://gems.hashicorp.com/specs.4.8.gz)" 

I downloaded specs.4.8.gz but am not sure what to do next. 

Thanks for your help in advance.

**Comment by fnordfish** [comment]
Oh darn, right. It tries to check all dependencies again. Bundler (the thing vagrant uses internally to manage plugins) has a `--local` switch, which would do what you want. `vagrant plugin install` has the same switch, but does something else.

Sorry to say, but there's no easy way for me to figure this out. Please ask the folks over at the vargrant project directly. From my side, those two files is all you should need (micromachine does not have any dependencies, all other dependencies of vagrant-vbguest are satisfied by vagrant)

**Comment by sssignals** [comment]
Thanks fnordfish for the verification.
