### ISSUE TITLE
Enhancement: Support installing only if missing

### ISSUE THREAD

**Issue by jakecobb** [dotless-de/vagrant-vbguest#375]
As an enhancement, it would be nice if it could be configured to install only when missing.  Setting `auto_update` to `false` currently prevents installing at all.  This plugin is good e.g. for working around broken Vagrant boxes that are missing the guest additions in the base image, but then the `vagrant up` time can increase substantially for boxes that already have a slightly older version than the current Virtualbox.

**Comment by fnordfish** [comment]
Sound's like a good idea. I guess having `auto_update = :missing` would even be backwards compatible.
