### ISSUE TITLE
running detection broken on older kernels

### ISSUE THREAD

**Issue by asharpe** [dotless-de/vagrant-vbguest#376]
I'm making a bit of an assumption about "older kernels", however the change that appears to have caused this issue was c8b45ff00f9d9bc496d53685ede7d2d9573457cc

This change causes the guest additions to be re-compiled, and the VM rebooted on every normal VM boot.

On an older kernel the grep on `/proc/modules` can't find what we're looking for (this is a scientific linux 6.10 VM)

```
# uname -r
2.6.32-754.29.1.el6.x86_64
# grep ^vbox /proc/modules
vboxsf 71439 1 - Live 0xffffffffa0404000
vboxguest 337234 2 vboxsf, Live 0xffffffffa0267000
```

Note that the the lines for those modules don't include the "0" which appears on newer kernels

```
# uname -r
3.10.0-1127.el7.x86_64
# grep ^vbox /proc/modules
vboxsf 81052 1 - Live 0xffffffffc081b000 (OE)
vboxvideo 35867 0 - Live 0xffffffffc0778000 (OE)
vboxguest 349038 2 vboxsf, Live 0xffffffffc05f0000 (OE)
```

**Comment by asharpe** [comment]
This was foreseen https://github.com/dotless-de/vagrant-vbguest/pull/334#pullrequestreview-233746843

**Comment by Morac2** [comment]
I found it after the fact.  It was never fixed.   I opened an issue #347 and it got closed because it was stale.

I decided to just create a pull request to fix it.  
#377
