### ISSUE TITLE
Cannot add vbox additions on Windows 10

### ISSUE THREAD

**Issue by mladenuzelac** [dotless-de/vagrant-vbguest#379]
Hi,

When I run vagrant up on Windows 7 everything runs fine (Virtualbox 6.1.10 and Vagrant 2.2.9 and vbguest 0.24)
When I try that on Windows 10 I get this error:

C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/net-ssh-5.2.0/lib/net/ssh/buffered_io.rb:66:in `recv': An existing connection was forcibly closed by the remote host. - recvfrom(2) (Errno::ECONNRESET)

**Comment by Rulac** [comment]
Hi,

Same on Windows 10.

**Comment by fnordfish** [comment]
Can you please run vagrant in debug mode and attach its log output here.

**Comment by mladenuzelac** [comment]
> Can you please run vagrant in debug mode and attach its log output here.

I sent in an email since the file is almost 500kb big.

**Comment by fnordfish** [comment]
Looking through the logs it seems, that SSH communication with the guest is OK, but uploading the ISO via SCP fails.
@thumperward Any ideas?

**Comment by thumperward** [comment]
I can't reproduce this (Windows 10, Virtualbox 6.1.10, Vagrant 2.2.9, vbguest 0.24) - copying the iso succeeds for me:

```
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (6.1.10) and guest (6.1.2) do not match.
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box $env:TEMP/VBoxGuestAdditions.iso


Attached          : True
BlockSize         : 0
DevicePath        : \\.\CDROM0
FileSize          : 60448768
ImagePath         : C:\Users\vagrant\AppData\Local\Temp/VBoxGuestAdditions.iso
LogicalSectorSize : 2048
Number            : 0
Size              : 60448768
StorageType       : 1
PSComputerName    :



Mounting Virtualbox Guest Additions ISO to: D
```

fwiw I used Windows 10 when developing Windows support.

@fnordfish - can you provide the relevant parts from the debug log?

**Comment by fnordfish** [comment]
I've just put the log provided by @Rulac in a gist: https://gist.github.com/fnordfish/43805b4e2f5f2e4420152d9df69e8b24
The trace is at the very end. But there's not much to see there.

@thumperward  But reading through the log again, it's not an issue with a windows guest. The host is windows 10, but the guest is centos 7. Sorry for the noise.

**Comment by Rulac** [comment]
I think this is not vagrant-vbguest issue. Problem is in Vagrant itself.

I have the same error without vagrant-vbguest plugin installed and [vagrant upload](https://www.vagrantup.com/docs/cli/upload) command:
vagrant upload "C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso" /tmp

@mladenuzelac Do you have Docker on Windows 10?


I solved the problem with:
1. [Set Core Isolation Memory Integrity to Off](https://www.howtogeek.com/357757/what-are-core-isolation-and-memory-integrity-in-windows-10/)
2. run in CMD:
 [`bcdedit /set hypervisorlaunchtype off`](https://stackoverflow.com/a/50119065) 
3. restart

**Comment by mladenuzelac** [comment]
I have Docker on Windows 10, I check these settings.

**Comment by jserra91** [comment]
Hello @Rulac 

Thank you, this is the problem 👍 

Regards and a beer for you!

**Comment by BRAiNCHiLD95** [comment]
I'm running Windows 10 Home, so Hyper-V is unavailable, also Core Isolation/Memory Integrity was OFF by default.
So,
The solution in my case was to use "virtualbox" as the type for synced_folders - 

`config.vm.synced_folder ".", "/vagrant", type: "virtualbox"`

And also, inside the config specific to provider - 


`config.vm.provider "virtualbox" do |vb|`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`# Allow shared folders sym linking`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]`
`end`

Note that **/vagrant** is the path I use inside my virtual machine - therefore that's the path added at the end of SharedFoldersEnableSymlinksCreate.

Did both of these - and Guest Additions were installed/updated, and also fixed most issues with npm/yarn and composer.

**Comment by mladenuzelac** [comment]
There are some issues regarding newer Windows 10 pro edition and virtualbox. 
So I don't try to use Vbox at all, I use WSL2 these days.
