### ISSUE TITLE
Installation is broken on CentOS-8

### ISSUE THREAD

**Issue by AlexBaranowski** [dotless-de/vagrant-vbguest#382]
# Steps to reproduce

1. `vagrant init eurolinux-vagrant/centos-8`
2. `vagrant up --provider virtualbox`

Output:
```
Error: Unknown repo: 'C*-base'
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates

Stdout from the command:



Stderr from the command:

Error: Unknown repo: 'C*-base'

```

## Reason why this fails

The problem is that CentOS-8 don't uses `base` and `updates` repo. (Now it's BaseOS and AppStream, both have updates within repo).

From lib/vagrant-vbguest/installers/centos.rb:

```
yum repolist --enablerepo=C#{rel}-base --enablerepo=C#{rel}-updates
```

## How to fix

I'm not a ruby programmer so it will take me a considerable amount of time. But the easiest solution is to:

- Check if the running version is CentOS 8
- Remove `--enablerepo=C*-base --enablerepo=C*-updates` for C8.

I don't really get why even `--enablerepo=C*-base --enablerepo=C*-updates` is used on the first place. I never saw an image that has the most basic repos disabled.

**Comment by fnordfish** [comment]
Please give the just released v0.25.0 a try.
