### ISSUE TITLE
Vagrant error installing vbguest

### ISSUE THREAD

**Issue by Loganguy** [dotless-de/vagrant-vbguest#388]
vagrant 2.9 or 2.10 I tried both
mac os 10.15.7
I've never seen this error.  I removed vagrant and reinstalled twice.  There is a starfield cert in the keychain.  Any help is appreciated.

ERROR:  SSL verification error at depth 3: unable to get local issuer certificate (20)
ERROR:  You must add /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority to your local trusted store
Vagrant failed to initialize at a very early stage:

Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/

**Comment by fnordfish** [comment]
Sorry, can't help with that. It seems like an issue connecting to the hashicorp gem server (gems are basically ruby packages, the way vagrant plugins are distributed). The source could be anything from temp. mis-configuration of the server, some CDN, your ISP to your local ssl setup. If the problem persists, try the vagrant mailing list.
