### ISSUE TITLE
vbguest doesn't automaticaly run with Vagrant 2.2.13

### ISSUE THREAD

**Issue by PlqnK** [dotless-de/vagrant-vbguest#391]
Hi!

I'm using Vagrant 2.2.13 with Virtualbox 6.1.6 (r140961) on Windows 10 1909 (18363.1198) and I'm having trouble getting the plugin (v0.26.0) to work since my update from Vagrant 2.2.10.

Here's a sample Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vbguest.auto_update = true
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
end
```

Here's the output of a `vagrant up` on this Vagrantfile:

```text
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' version '2004.01' is up to date...
==> default: Setting the name of the VM: test_default_1605265863064_13269
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/Victor.BOUVIERDELEAU/Downloads/test
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: unknown filesystem type 'vboxsf'
```

As you can see the plugin was not called by Vagrant!

If I run `vagrant vbguest --status` I get:

```text
[default] No Virtualbox Guest Additions installation found.
```

And manual installation using `vagrant vbguest --do install` does work so I'm tempted to say that this is a regression in Vagrant itself, are you able to confirm that? If it's the case then I will open an issue on their repo!

Thanks a lot for your work!

EDIT: I forgot to mention that I did this test without any `Vagrantfile` in my `~/.vagrant.d` overriding anything.

**Comment by vadbes46** [comment]
same for me on 2.2.13

**Comment by fnordfish** [comment]
I've opened an issue at vagrant to see what's the best approach on this. https://github.com/hashicorp/vagrant/issues/12046

**Comment by keks24** [comment]
As a temporary workaround, you might consider falling back to an older version of `vagrant`:

https://releases.hashicorp.com/vagrant/

**Comment by fnordfish** [comment]
It's a vagrant bug. See: https://github.com/hashicorp/vagrant/issues/12035
There's fix in the form of a test package available: https://github.com/hashicorp/vagrant/issues/12035#issuecomment-725595346

**Comment by fnordfish** [comment]
released v0.28.0 with a work around for vagrant 2.2.11 to 2.2.13. Please upgrade to vagrant 2.2.14 when it gets out, or use the pre-release linked in https://github.com/hashicorp/vagrant/issues/12035#issuecomment-725595346

**Comment by keks24** [comment]
Looks good to me!:

```bash
$ vagrant --version
Vagrant 2.2.14
```

```bash
$ vagrant plugin list
vagrant-vbguest (0.28.0, global)
  - Version Constraint: > 0
```

Thanks for the effort!

**Comment by jakec-dev** [comment]
I'm getting this issue with Vagrant v2.2.16. It seems to fix itself if I run `vagrant reload`, but it's annoying having to do this every time I create a new vm. Is this an ongoing issue or could something else possibly be causing this?

**Comment by fnordfish** [comment]
@jakec-dev Looks like a different issue. vbguest did run on the first "up", hence all the `VirtualBox Guest Additions:` lines. But the updated additions didn't come into effect until you used `reload` to reboot the vm.
