### ISSUE TITLE
VirtualBox Guest Additions Upgade failed

### ISSUE THREAD

**Issue by IIM-Andreas** [dotless-de/vagrant-vbguest#404]
Hi,

I wanna upgrade VirtualBox Guest Additions from Version 5.2.44 to 6.0.8 on this debian9/stretch Box (https://app.vagrantup.com/amonteilhet/boxes/debian-stretch64).

> [default] GuestAdditions versions on your host (6.0.8) and guest (5.2.44) do not match.
> Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
> Mounting Virtualbox Guest Additions ISO to: /mnt
> mount: /dev/loop0 is write-protected, mounting read-only
> Installing Virtualbox Guest Additions 6.0.8 - guest version is 5.2.44
> Verifying archive integrity... All good.
> Uncompressing VirtualBox 6.0.8 Guest Additions for Linux........
> VirtualBox Guest Additions installer
> Removing installed version 5.2.44 of VirtualBox Guest Additions...
> Copying additional installer modules ...
> Installing additional modules ...
> VirtualBox Guest Additions: Starting.
> VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
> modules.  This may take a while.
> VirtualBox Guest Additions: To build modules for other installed kernels, run
> VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
> VirtualBox Guest Additions: or
> VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
> VirtualBox Guest Additions: Building the modules for kernel 4.9.0-14-amd64.
> update-initramfs: /boot/initrd.img-4.9.0-14-amd64 has been altered.
> update-initramfs: Cannot update. Override with -t option.
> VirtualBox Guest Additions: Running kernel modules will not be replaced until 
> the system is restarted
> An error occurred during installation of VirtualBox Guest Additions 6.0.8. Some functionality may not work as intended.
> In most cases it is OK that the "Window System drivers" installation failed.
> Unmounting Virtualbox Guest Additions ISO from: /mnt
> Got different reports about installed GuestAdditions version:
> 
> VBoxService inside the vm claims: 6.0.8
> Going on, assuming VBoxService is correct...
> Got different reports about installed GuestAdditions version:
> Virtualbox on your host claims:   5.2.44
> VBoxService inside the vm claims: 6.0.8
> Going on, assuming VBoxService is correct...
> ==> default: Checking for guest additions in VM...
>     default: The guest additions on this VM do not match the installed version of
>     default: VirtualBox! In most cases this is fine, but in rare cases it can
>     default: prevent things such as shared folders from working properly. If you see
>     default: shared folder errors, please make sure the guest additions within the
>     default: virtual machine match the version of VirtualBox you have installed on
>     default: your host and reload your VM.
>     default: 
>     default: Guest Additions Version: 5.2.44
>     default: VirtualBox Version: 6.0

after vagrant reload (every reload/start) it detects that:

> [default] GuestAdditions seems to be installed (6.0.8) correctly, but not running.
> update-initramfs: /boot/initrd.img-4.9.0-14-amd64 has been altered.
> update-initramfs: Cannot update. Override with -t option.
> VirtualBox Guest Additions: Starting.
> VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
> modules.  This may take a while.
> VirtualBox Guest Additions: To build modules for other installed kernels, run
> VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
> VirtualBox Guest Additions: or
> VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
> VirtualBox Guest Additions: Building the modules for kernel 4.9.0-14-amd64.
> update-initramfs: /boot/initrd.img-4.9.0-14-amd64 has been altered.
> update-initramfs: Cannot update. Override with -t option.
> VirtualBox Guest Additions: Running kernel modules will not be replaced until 
> the system is restarted
> Restarting VM to apply changes...

So it seems the kernel was not updated:

> [default] GuestAdditions seems to be installed (6.0.8) correctly, but not running.
> update-initramfs: /boot/initrd.img-4.9.0-14-amd64 has been altered.
> update-initramfs: Cannot update. Override with -t option.

But how can I force the override in vagrantfile? What's the solution for this?

Using Win10
Virtualbox 6.0.8
Vagrant 2.2.6
vagrant-vbguest 0.29.0

**Comment by fnordfish** [comment]
For a while VirtualBox Guest Additions prints this message, and I'm trying to figure out, if it would benefit if vbguest just does that by default. Can you try adding this config to your Vagrantfile:

```ruby
config.vbguest.installer_hooks[:after_install] = ["/sbin/rcvboxadd quicksetup all"]
```

(whre `config` is your boxes config if you use multiple boxes in one vagrant project, or directly the `config` of the `Vagrant.configure("2") do |config|` block - if in doubt, post your Vagrantfile)

This `update-initramfs` things also cought my eye, so either `rcvboxadd quicksetup` will take care of that, or you need to execute that manually or try using the after install hook again:

```ruby
config.vbguest.installer_hooks[:after_install] = [
  "/sbin/rcvboxadd quicksetup all",
  "update-initramfs -u -t"
]
```

if any of that did the trick, please let me know, or post an entry in our new discussions section https://github.com/dotless-de/vagrant-vbguest/discussions

**Comment by IIM-Andreas** [comment]
I tried it with both variants.

`config.vbguest.installer_hooks[:after_install] = [
  "/sbin/rcvboxadd quicksetup all",
  "update-initramfs -u -t"
]`

`==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (6.0.8) and guest (5.2.44) do not match.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version (2.3-2).
linux-headers-4.9.0-14-amd64 is already the newest version (4.9.246-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 6.0.8 - guest version is 5.2.44
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.0.8 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 5.2.44 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 4.9.0-14-amd64.
update-initramfs: /boot/initrd.img-4.9.0-14-amd64 has been altered.
update-initramfs: Cannot update. Override with -t option.
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted
An error occurred during installation of VirtualBox Guest Additions 6.0.8. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
**==> default: Executing post-install hooks**
update-initramfs: Generating /boot/initrd.img-4.9.0-14-amd64
Unmounting Virtualbox Guest Additions ISO from: /mnt
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.2.44
VBoxService inside the vm claims: 6.0.8
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.2.44
VBoxService inside the vm claims: 6.0.8
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.2.44
    default: VirtualBox Version: 6.0
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...

Process finished with exit code 0


Reload:

==> default: Machine booted and ready!
[default] GuestAdditions seems to be **installed (6.0.8) correctly, but not running**.
update-initramfs: Generating /boot/initrd.img-4.9.0-14-amd64
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 4.9.0-14-amd64.
update-initramfs: Generating /boot/initrd.img-4.9.0-14-amd64
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted
Restarting VM to apply changes...
==> default: Attempting graceful shutdown of VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

Process finished with exit code 0`

But it still says not running on every start.

**Comment by fnordfish** [comment]
At least, we got a bit further. However, I just tested with https://app.vagrantup.com/debian/boxes/stretch64 and things work.
So I wonder what might be different between those boxes. Maybe there's another non-standard installation using some packages, or some other changes in that box preventing a working install. If there's a reason to why you are using that specific box, I would like to ask you to reach out to the author/maintainer of that box asking for advise.

**Comment by kotech1** [comment]
I had the simlilar problem. 

host OS: osx big sur
virtualbox: 6.1.16
vagrant: 2.2.14
vagrant-vbguest version: 0.29.0
guest OS: ubuntu 16.04

In my case, the reason was the vbguest checks vboxguest and vboxsf in `/proc/moduels`.
Without any mounts with `vboxsf`, the `vagrant-vbguest` plugin fails to check the running state.

Can you try with the mount options added like this?
`config.vm.synced_folder '.', '/vagrant', disabled: false, type: 'virtualbox'`

Once mounted, then the `vboxsf` will be reloaded autmatically after removing mounts.

You can remove `vboxsf` item from the plugin source if you don't want any mounts.

**Comment by shevious** [comment]
I had similar problem.
host OS: big sur,
guest OS: ubuntu 16.04
virtualbox 6.1.16
vagrant-vbguest: 0.29.0

My problem was the `vbguest` plugin searches `vboxguest` and `vboxsf` in `/proc/modules` in the guest.
But `vboxsf` module does not exist if there is no vboxsf mounting exists.

Can you try mounts with vboxsf in your Vagrantfile?
`config.vm.synced_folder '.', '/vagrant', disabled: false, type: 'virtualbox'`

Once mounted, the `vboxsf` module will be loaded automatically after removing mounts.

You can remove `vboxsf` element from the plugin source if you don't want any mounts.

**Comment by fnordfish** [comment]
So, you say the vboxsf module might be auto loaded on demand? That would be interesting and vbguest could eventually try to detect this. 

In the mean time, you can disable vboxsf detection in your Vagrantfile: https://github.com/dotless-de/vagrant-vbguest#linux

**Comment by joeymart** [comment]
> So, you say the vboxsf module might be auto loaded on demand? That would be interesting and vbguest could eventually try to detect this.
> 
> In the mean time, you can disable vboxsf detection in your Vagrantfile: https://github.com/dotless-de/vagrant-vbguest#linux

This fixed this issue for me using the box `bento/centos7-8`. 

VagrantFile:
```
Vagrant.configure('2') do |config|

  config.vm.define :centos78 do |config|
    config.vm.box = "bento/centos-7.8"
    
    config.vm.network 'private_network', ip: '192.168.1.11', 
      virtualbox__intnet: 'mynetwork'
    
    config.vm.host_name = 'centos78.localdomain'
    config.vm.network "forwarded_port", guest: 16002, host:16002
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

end
```
Result: 
```
~/vagranttest$ vagrant up
Bringing machine 'centos78' up with 'virtualbox' provider...
==> centos78: Checking if box 'bento/centos-7.8' version '202010.22.0' is up to date...
==> centos78: Fixed port collision for 22 => 2222. Now on port 2200.
==> centos78: Clearing any previously set network interfaces...
==> centos78: Preparing network interfaces based on configuration...
    centos78: Adapter 1: nat
    centos78: Adapter 2: intnet
==> centos78: Forwarding ports...
    centos78: 16002 (guest) => 16002 (host) (adapter 1)
    centos78: 22 (guest) => 2200 (host) (adapter 1)
==> centos78: Booting VM...
==> centos78: Waiting for machine to boot. This may take a few minutes...
    centos78: SSH address: 127.0.0.1:2200
    centos78: SSH username: vagrant
    centos78: SSH auth method: private key
    centos78: Warning: Connection reset. Retrying...
    centos78: Warning: Remote connection disconnect. Retrying...
    centos78: Warning: Connection reset. Retrying...
    centos78: Warning: Remote connection disconnect. Retrying...
    centos78: Warning: Connection reset. Retrying...
    centos78: Warning: Remote connection disconnect. Retrying...
    centos78:
    centos78: Vagrant insecure key detected. Vagrant will automatically replace
    centos78: this with a newly generated keypair for better security.
    centos78:
    centos78: Inserting generated public key within guest...
    centos78: Removing insecure key from the guest if it's present...
    centos78: Key inserted! Disconnecting and reconnecting using new SSH key...
==> centos78: Machine booted and ready!
 INFO vbguest-machine: initialize vbguest machine for VM 'centos78' (#<Vagrant::Machine:0x00007f8eed0d0420>)
 INFO vbguest-machine: Current states for VM 'centos78' are : guest_version=6.1.16 : host_version=6.1.16 : running=false
[centos78] GuestAdditions seems to be installed (6.1.16) correctly, but not running.
 INFO vbguest-machine: Current states for VM 'centos78' are : guest_version=6.1.16 : host_version=6.1.16 : running=false
 INFO vbguest-machine: Runlist for state not_running is: [:start, :rebuild, :reboot]
 INFO vbguest-machine: Running command start from runlist
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
 INFO vbguest-machine: Current states for VM 'centos78' are : guest_version=6.1.16 : host_version=6.1.16 : running=false
 INFO vbguest-machine: Running command rebuild from runlist
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Kernel headers not found for target kernel
3.10.0-1127.19.1.el7.x86_64. Please install them and execute
  /sbin/rcvboxadd setup
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
 INFO vbguest-machine: Current states for VM 'centos78' are : guest_version=6.1.16 : host_version=6.1.16 : running=false
 INFO vbguest-machine: Running command reboot from runlist
 INFO vbguest-machine: Current states for VM 'centos78' are : guest_version=6.1.16 : host_version=6.1.16 : running=false
Restarting VM to apply changes...
==> centos78: Attempting graceful shutdown of VM...
==> centos78: Booting VM...
==> centos78: Waiting for machine to boot. This may take a few minutes...
==> centos78: Machine booted and ready!
==> centos78: Checking for guest additions in VM...
    centos78: No guest additions were detected on the base box for this VM! Guest
    centos78: additions are required for forwarded ports, shared folders, host only
    centos78: networking, and more. If SSH fails on this machine, please install
    centos78: the guest additions and repackage the box to continue.
    centos78:
    centos78: This is not an error message; everything may continue to work properly,
    centos78: in which case you may ignore this message.
==> centos78: Setting hostname...
==> centos78: Configuring and enabling network interfaces...
==> centos78: Mounting shared folders...
    centos78: /vagrant => /Users/joey.mart/vagranttest
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

Added the `installer_options` line to the VagrantFile:
```
Vagrant.configure('2') do |config|

  config.vm.define :centos78 do |config|
    config.vm.box = "bento/centos-7.8"
    config.vbguest.installer_options = { running_kernel_modules: ["vboxguest"] }

    config.vm.network 'private_network', ip: '192.168.1.11', 
      virtualbox__intnet: 'mynetwork'
    
    config.vm.host_name = 'centos78.localdomain'
    config.vm.network "forwarded_port", guest: 16002, host:16002
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

end
```

Result: 
```
~/vagranttest$ vagrant up
Bringing machine 'centos78' up with 'virtualbox' provider...
==> centos78: Importing base box 'bento/centos-7.8'...
==> centos78: Matching MAC address for NAT networking...
==> centos78: Checking if box 'bento/centos-7.8' version '202010.22.0' is up to date...
==> centos78: Setting the name of the VM: vagranttest_centos78_1611774978344_69629
==> centos78: Fixed port collision for 22 => 2222. Now on port 2200.
==> centos78: Clearing any previously set network interfaces...
==> centos78: Preparing network interfaces based on configuration...
    centos78: Adapter 1: nat
    centos78: Adapter 2: intnet
==> centos78: Forwarding ports...
    centos78: 16002 (guest) => 16002 (host) (adapter 1)
    centos78: 22 (guest) => 2200 (host) (adapter 1)
==> centos78: Booting VM...
==> centos78: Waiting for machine to boot. This may take a few minutes...
    centos78: SSH address: 127.0.0.1:2200
    centos78: SSH username: vagrant
    centos78: SSH auth method: private key
    centos78: Warning: Connection reset. Retrying...
    centos78: Warning: Remote connection disconnect. Retrying...
    centos78: Warning: Connection reset. Retrying...
    centos78: Warning: Remote connection disconnect. Retrying...
    centos78: Warning: Connection reset. Retrying...
    centos78:
    centos78: Vagrant insecure key detected. Vagrant will automatically replace
    centos78: this with a newly generated keypair for better security.
    centos78:
    centos78: Inserting generated public key within guest...
    centos78: Removing insecure key from the guest if it's present...
    centos78: Key inserted! Disconnecting and reconnecting using new SSH key...
==> centos78: Machine booted and ready!
 INFO vbguest-machine: initialize vbguest machine for VM 'centos78' (#<Vagrant::Machine:0x00007f996e921ff8>)

 INFO vbguest-machine: Current states for VM 'centos78' are : guest_version=6.1.16 : host_version=6.1.16 : running=true
[centos78] GuestAdditions 6.1.16 running --- OK.
 INFO vbguest-machine: Current states for VM 'centos78' are : guest_version=6.1.16 : host_version=6.1.16 : running=true
 INFO vbguest-machine: Runlist for state ok is: []
==> centos78: Checking for guest additions in VM...
==> centos78: Setting hostname...
==> centos78: Configuring and enabling network interfaces...
==> centos78: Mounting shared folders...
    centos78: /vagrant => /Users/joey.mart/vagranttest
```
