### ISSUE TITLE
Guest additions fails to install correctly, fails to startup with every `vagrant up`

### ISSUE THREAD

**Issue by jakec-dev** [dotless-de/vagrant-vbguest#414]
- Vagrant version 2.2.16
- vagrant-vbguest version 0.30.0

Output during initial creation of vm:

```
[default] GuestAdditions versions on your host (6.1.22) and guest (5.2.44) do not match.
Extra Packages for Enterprise Linux Modular 8 -  23 kB/s |  37 kB     00:01    
Extra Packages for Enterprise Linux Modular 8 - 109 kB/s | 663 kB     00:06    
Extra Packages for Enterprise Linux 8 - x86_64  9.4 kB/s | 9.7 kB     00:01    
Extra Packages for Enterprise Linux 8 - x86_64  1.3 MB/s |  10 MB     00:07    
Last metadata expiration check: 0:00:02 ago on Mon 05 Jul 2021 04:14:20 AM UTC.
Package kernel-devel-4.18.0-240.el8.x86_64 is already installed.
Package kernel-devel-4.18.0-240.el8.x86_64 is already installed.
Package gcc-8.3.1-5.1.el8.x86_64 is already installed.
Package binutils-2.30-79.el8.x86_64 is already installed.
Package make-1:4.2.1-10.el8.x86_64 is already installed.
Package perl-interpreter-4:5.26.3-416.el8.x86_64 is already installed.
Package bzip2-1.0.6-26.el8.x86_64 is already installed.
Package elfutils-libelf-devel-0.180-1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Copy iso file /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /mnt: WARNING: device write-protected, mounted read-only.
Installing Virtualbox Guest Additions 6.1.22 - guest version is 5.2.44
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.1.22 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 5.2.44 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 
4.18.0-240.el8.x86_64.
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted
An error occurred during installation of VirtualBox Guest Additions 6.1.22. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Unmounting Virtualbox Guest Additions ISO from: /mnt
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.2.44
VBoxService inside the vm claims: 6.1.22
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.2.44
VBoxService inside the vm claims: 6.1.22
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.2.44
    default: VirtualBox Version: 6.1
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/jake/VMs/lab/rhel8
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000,_netdev vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: Invalid argument
```

Output every single time I run `vagrant up` (after running `vagrant halt`) or `vagrant reload`:

```
[default] GuestAdditions seems to be installed (6.1.22) correctly, but not running.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 
4.18.0-240.el8.x86_64.
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted
Restarting VM to apply changes...
```
After the restart it works fine.

This happens every single time I run `vagrant up`. I can see that both `vboxadd.service` and `vboxadd-service.service` are enabled in systemd.

Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

unregister_script = %{
if subscription-manager status; then
  sudo subscription-manager unregister
fi
}

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-env", "vagrant-vbguest"]
  config.env.enable # https://github.com/gosuri/vagrant-env

  config.vm.box = "generic/rhel8"
  config.vm.hostname = "JC-VM-lab-rhel8"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "lab-rhel8"
    vb.gui = true
    vb.cpus = 4
    vb.memory = 4096
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end  

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "public_network", bridge: "wlp6s0"
  
  config.vm.provision "shell", path: "bootstrap.sh", args: "#{ENV['RH_SUBSCRIPTION_USER']} #{ENV['RH_SUBSCRIPTION_PW']}"

  config.vm.synced_folder ".", "/vagrant"

  config.trigger.before :destroy do |trigger|
    trigger.name = "Before Destroy Trigger"
    trigger.info = "Unregistering this VM from Red Hat Subscription Manager"
    trigger.warn = "If this fails, unregister VMs manually at https://access.redhat.com/management/subscriptions"
    trigger.run_remote = {inline: unregister_script}
    trigger.on_error = :continue
  end
end
```

**Comment by jakec-dev** [comment]
I'm now getting this message too:

```
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported
```

**Comment by jakec-dev** [comment]
`vagrant vbguest --status` returns `[default] GuestAdditions seems to be installed (6.1.22) correctly, but not running.`, so it appears there is definitely a bug with vagrant-vbguest. It seems to install fine, but it doesn't run at startup.

Is anyone able to assist? I really want to get this working properly ASAP as I don't want to create any new VMs until this bug is fixed.

**Comment by jakec-dev** [comment]
Adding `config.vbguest.installer_options = {enablerepo: true, allow_kernal_upgrade: true}` to Vagrantfile doesn't help either

**Comment by jakec-dev** [comment]
Followed advice from  which leads to an improvement at least:

`vagrant vbguest --status` output:
```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.2.44
VBoxService inside the vm claims: 6.1.22
Going on, assuming VBoxService is correct...
[default] GuestAdditions 6.1.22 running --- OK
```

So the manual installer seems to work ok, it's just vbguest installer script I guess that's causing issues. Still doesn't fix the mismatched versions though, which is the entire reason for using vagrant-vbguest, so still more debugging to do.

**Comment by jakec-dev** [comment]
Also can't use ` config.vm.provision "file", source: "path/to/source", destination: "path/to/destination"` either as it returns:

```
default: Running provisioner: file...
Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.
```

**Comment by pl4g4** [comment]
I'm getting the exact same issue. Looks like the service fails 

`root@master:~# systemctl status vboxadd-service.service
* vboxadd-service.service
   Loaded: loaded (/opt/VBoxGuestAdditions-6.1.22/init/vboxadd-service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-07-08 15:02:49 UTC; 2min 6s ago
  Process: 11292 ExecStart=/opt/VBoxGuestAdditions-6.1.22/init/vboxadd-service start (code=exited, status=1/FAILURE)

Jul 08 15:02:49 master systemd[1]: Starting vboxadd-service.service...
Jul 08 15:02:49 master vboxadd-service[11292]: vboxadd-service.sh: Starting VirtualBox Guest Addition service.
Jul 08 15:02:49 master systemd[1]: vboxadd-service.service: Control process exited, code=exited status=1
Jul 08 15:02:49 master systemd[1]: Failed to start vboxadd-service.service.
Jul 08 15:02:49 master systemd[1]: vboxadd-service.service: Unit entered failed state.
Jul 08 15:02:49 master systemd[1]: vboxadd-service.service: Failed with result 'exit-code'.
`

same settings 

Vagrant version 2.2.16
vagrant-vbguest version 0.30.0

+ virtualbox 6.1.22

**Comment by Zorgji** [comment]
@jakec-dev 
`Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000,_netdev home_vagrant /home/vagrant

The error output from the command was:

: Invalid argument`

**Comment by pl4g4** [comment]
as for now, I was able to get pass that error by downgrading vagrant + virtualbox + VBoxGuestAdditions. 

VB 6.1.10 
Vagrant 2.2.7 
VBoxGuestAdditions 6.1.10

Works as expected, I'm not gonna update to the latest versions for now.

**Comment by Zorgji** [comment]
@pl4g4  Yeah Don't do it for now.

**Comment by lubo** [comment]
I've noticed that this only happens on machines which don't use shared folders. As a workaround, you can put `vboxsf` into a file in `/etc/modules-load.d`. You can use `shell` provisioner to create the file automatically.

**Comment by magnetik** [comment]
Facing the same issue. There is a bug ongoing (without much info in it) on bento side : https://github.com/chef/bento/issues/1363

**Comment by Zorgji** [comment]
Accidentally mine was solved, I completely uninstalled both `VitualBox`, `Vagrant` shut down Mac, and waited for a while, and switch on, once bootup installed the latest ones. Now all working well. 
```
No plugins installed on vagrant.
Vagrant Version: 2.2.18
VirtualBox version: 6.1.22r144080
```

**Comment by brettt89** [comment]
For Debian based builds, I was able to resolve this by installing `virtualbox-guest-utils` on the guest.

```
apt install -y virtualbox-guest-utils
systemctl enable --now virtualbox-guest-utils
```

Reference: https://github.com/chef/bento/issues/1185

**Comment by gesinn-it** [comment]
I had the same issue with
```
 config.vm.box = "debian/buster64"
 config.vm.box_version = "10.20210409.1"
```
but not with
```
 config.vm.box = "bento/debian-10"
 config.vm.box_version = "202107.08.0"
```

**Comment by zentavr** [comment]
this worked for me:
```
sudo apt install virtualbox-guest-utils=6.1.16-dfsg-6~ubuntu1.20.04.2
```
I did not downgraded vagrant/Virtualbox on MacOS.

The whole log is:
```
vagrant@resecs-livecd:~$ sudo apt install virtualbox-guest-utils=6.1.16-dfsg-6~ubuntu1.20.04.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  virtualbox-guest-x11
The following packages will be DOWNGRADED:
  virtualbox-guest-utils
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
Need to get 871 kB of archives.
After this operation, 1024 B disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 virtualbox-guest-utils amd64 6.1.16-dfsg-6~ubuntu1.20.04.2 [871 kB]
Fetched 871 kB in 1s (608 kB/s)
dpkg: warning: downgrading virtualbox-guest-utils from 6.1.22-dfsg-2~ubuntu1.20.04.1 to 6.1.16-dfsg-6~ubuntu1.20.04.2
(Reading database ... 63621 files and directories currently installed.)
Preparing to unpack .../virtualbox-guest-utils_6.1.16-dfsg-6~ubuntu1.20.04.2_amd64.deb ...
Unpacking virtualbox-guest-utils (6.1.16-dfsg-6~ubuntu1.20.04.2) over (6.1.22-dfsg-2~ubuntu1.20.04.1) ...
Setting up virtualbox-guest-utils (6.1.16-dfsg-6~ubuntu1.20.04.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.11) ...
vagrant@resecs-livecd:~$ sudo mount -t vboxsf -o uid=1000,gid=1000,_netdev opt_build /opt/build
```

**Comment by eldho-varghese** [comment]
Hi All

Same issue for me as well. 

[user@centos rhcsa8env]$ vagrant vbguest --status
[server2] GuestAdditions seems to be installed (6.1.26) correctly, but not running.
[repo] GuestAdditions seems to be installed (6.1.26) correctly, but not running.
[workstation] GuestAdditions seems to be installed (6.1.26) correctly, but not running.
[server1] GuestAdditions seems to be installed (6.1.26) correctly, but not running.
[user@centos rhcsa8env]$


However, All the boxes are up and running with guest addition services

[root@server2 ~]# systemctl list-units |grep vboxadd
vboxadd-service.service                                                                  loaded active running   vboxadd-service.service
vboxadd.service                                                                          loaded active exited    vboxadd.service
[root@server2 ~]#

following modules are loaded, However I can't see "vboxsf"  and "vboxadd" module as loaded
[root@server2 ~]# lsmod |grep vbox
vboxvideo              49152  1
drm_kms_helper        200704  1 vboxvideo
ttm                   131072  1 vboxvideo
drm                   520192  4 drm_kms_helper,vboxvideo,ttm
vboxguest             393216  1
[root@server2 ~]#

and the service startup script  "/opt/VBoxGuestAdditions-6.1.26/init/vboxadd"  always  build the module for kernel.
Could be the modules are not loaded correctly ? Why vagrant thinks thinks guest additions are installed but not running ?

[user@centos ~]$ vboxmanage --version
6.1.26r145957
[user@centos ~]$ vagrant --version
Vagrant 2.2.18
[user@centos ~]$ vagrant plugin list
vagrant-guest_ansible (0.0.4, global)
  - Version Constraint: > 0
vagrant-vbguest (0.30.0, global)
[user@centos ~]$
