### ISSUE TITLE
Disable 'Checking for guest additions in VM' per VM

### ISSUE THREAD

**Issue by bbaassssiiee** [dotless-de/vagrant-vbguest#420]
Is there a parameter to disable the plugin per VM?

**Comment by fnordfish** [comment]
All the options work on a vm config. `vbguest.auto_update = false` should do what you want (?). It will still check and print messages but don't *do* anything. 
There's no option to disable vbguest completely

**Comment by bbaassssiiee** [comment]
- Checking, can that be disabled?
- Printing messages, can that be disabled?

**Comment by bbaassssiiee** [comment]
Please add the option to disable vbguest completely. Feature-toggle.
