### ISSUE TITLE
vbguest should have the default autoupdate value configurable

### ISSUE THREAD

**Issue by ssbarnea** [dotless-de/vagrant-vbguest#422]
While working on resurrecting the test unit of https://github.com/pycontribs/python-vagrant project, I faced a serious issue: once the vbguest plugin gets installed, it broke the test suites, mainly because it attempted to perform an autoupdate which was not really possible.

While I had no problem adding the autoupdate = false to some of the hardcoded test files, we also have another set which is dynamic, for example we use `vagrant init` to create new configs,... and guess what, they do not have the workaround in them and there is no command line arguments for init to add extra configuration to them.

IMHO, we need an option to configure this plugin defaults so it would be possible to install it without messing other vagrant boxes.

Does anyone has an workaround for this issue?

**Comment by fnordfish** [comment]
Maybe this helps: https://www.vagrantup.com/docs/vagrantfile#load-order-and-merging

**Comment by ssbarnea** [comment]
Does `if config.instance_variable_defined?(:@vbguest) then config.vbguest.auto_update = false end` look as correct Ruby?

**Comment by fnordfish** [comment]
It does not look like it, but it is :) The more idiomatic way of writing this would be:

```ruby
config.vbguest.auto_update = false if config.instance_variable_defined?(:@vbguest)
```

But I wouldn't rely on `instance_variable_defined?` for code you don't have under control. b/c instance vars might be lazy defined and you might not hit it (checking it too early).

**Comment by fnordfish** [comment]
Vagrant has `Vagrant.has_plugin?("vagrant-vbguest")` - it's probably what you want to use

**Comment by fnordfish** [comment]
Is it possible to create a `$HOME/.vagrant.d/Vagrantfile` in your test environment? That should always be loaded and merged with the projects Vagrantfile.

**Comment by fnordfish** [comment]
I have no idea what you mean with "templates", but here's a minimal `$HOME/.vagrant.d/Vagrantfile` to disable vbguest auto update:

```ruby
Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
end
```

**Comment by konstruktoid** [comment]
I was thinking about `--template` (https://www.vagrantup.com/docs/cli/init#template-file).

**Comment by fnordfish** [comment]
I see. Never used those. But it's also not what you'd want. `vagrant init` creates a Vagrantfile for a new project. You probably can create a template and have that one line injected each time you create a project using that template. But simply creating a single `$HOME/.vagrant.d/Vagrantfile` once seems to be less work :) (see https://www.vagrantup.com/docs/vagrantfile#load-order)

**Comment by konstruktoid** [comment]
Indeed, thanks alot for you help @fnordfish
