### ISSUE TITLE
Support for AlmaLinux

### ISSUE THREAD

**Issue by alexgit2k** [dotless-de/vagrant-vbguest#430]
When using AlmaLinux with vbguest, the generic install is used:
`The guest's platform ("alma") is currently not supported, will try generic Linux method...`
However, the Guest Additions-installation can not be successfully completed, I am getting a deadlock after the module-reload.

There is already a installer for RHEL and Rocky Linux. As AlmaLinux is binary compatible with them the same installer should be used.

**Comment by fnordfish** [comment]
Please adopt your Vagrantfile and set `config.vbguest.installer = VagrantVbguest::Installers::RedHat` or `VagrantVbguest::Installers::CentOS`, depending on what works better for you.
I'm very hesitant of adding new platforms (even if they are supposed to be just the "same"), especially if its from the RHEL/CentOS  tree, as they tend to be quite a PITA.

**Comment by alexgit2k** [comment]
I provisioned several AlmaLinux-VMs with #431, and it works like a charm.
At the moment vanilla vagrant-vbguest is not working with AlmaLinux, that causes much more headaches to debug it.

Adding #431 will help some people, also Rocky Linux from the RHEL/CentOS tree was added as well in #424.

**Comment by marc-guenther** [comment]
It would have definitely helped me: #423
