### ISSUE TITLE
Guest installation freeze on virtual box 7.0.10

### ISSUE THREAD

**Issue by miyoku157** [dotless-de/vagrant-vbguest#432]
Hi,
I just updated virtualbox from 7.0.8 to 7.0.10 and vagrant just freeze without any logs : 
Here is the last logs i have before it stops
```
Processing triggers for man-db (2.9.4-2) ...
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /mnt: WARNING: source write-protected, mounted read-only.
Installing Virtualbox Guest Additions 7.0.10 - guest version is 6.0.0
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing VirtualBox 7.0.10 Guest Additions for Linux  100%
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Setting up modules
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 5.10.0-22-amd64.
update-initramfs: Generating /boot/initrd.img-5.10.0-22-amd64
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted or 'rcvboxadd reload' triggered
VirtualBox Guest Additions: reloading kernel modules and services
VirtualBox Guest Additions: kernel modules and services 7.0.10 r158379 reloaded
VirtualBox Guest Additions: NOTE: you may still consider to re-login if some
user session specific services (Shared Clipboard, Drag and Drop, Seamless or
Guest Screen Resize) were not restarted automatically
```

I'm on virtual box 7.0.10 and vagrant 2.3.7 and the box i'm trying to mount is a Debian 11. Am i the only one getting this?

**Comment by fnordfish** [comment]
The VirtualBox Guest Additions install logs look fine except for the missing unmount log: `Unmounting Virtualbox Guest Additions ISO from: /mnt`
Maybe `VBoxLinuxAdditions.run` does not exit for some reason?

**Comment by miyoku157** [comment]
Is there a way to get more logs from it? to see where it get stucks?
Am i the only one with this version getting this problem?

**Comment by eremem** [comment]
> Am i the only one with this version getting this problem?

No, you are not. I'm having exact the same problem. Vagrant 2.3.4, the rest seems to match.

**Comment by estribiyo** [comment]
Same for me, but I've changed my Debian.

Originally I was using this image: [debian/bullseye64](https://app.vagrantup.com/debian/boxes/bullseye64) but changing to this one: [generic/debian11](https://app.vagrantup.com/generic/boxes/debian11), goes like a charm... and doesn't freeze. Umounts the Guest Additions disk and continues...

```
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Setting up modules
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 5.10.0-21-amd64.
update-initramfs: Generating /boot/initrd.img-5.10.0-21-amd64
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted or 'rcvboxadd reload' triggered
VirtualBox Guest Additions: reloading kernel modules and services
VirtualBox Guest Additions: kernel modules and services 7.0.10 r158379 reloaded
VirtualBox Guest Additions: NOTE: you may still consider to re-login if some 
user session specific services (Shared Clipboard, Drag and Drop, Seamless or 
Guest Screen Resize) were not restarted automatically
An error occurred during installation of VirtualBox Guest Additions 7.0.10. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> ispconfig: Checking for guest additions in VM...
==> ispconfig: Setting hostname...
==> ispconfig: Configuring and enabling network interfaces...
==> ispconfig: Mounting shared folders...
```

**Comment by estribiyo** [comment]
In VirtualBox 6.1 works as espected, at first provision crashes (doesn't reload Guest Additions and can't mount shares) but in VirtualBox 7.0, when it freezes, logging into another terminal, and executing: `rcvboxadd reload`, it continues provisioning:

```
vagrant@bullseye:~$ sudo rcvboxadd reload
VirtualBox Guest Additions: reloading kernel modules and services
VirtualBox Guest Additions: kernel modules and services 7.0.10 r158379 reloaded
VirtualBox Guest Additions: NOTE: you may still consider to re-login if some
user session specific services (Shared Clipboard, Drag and Drop, Seamless or
Guest Screen Resize) were not restarted automatically
```

**Comment by eremem** [comment]
An alternative solution could be disabling the plugin at all as stated [here](https://wiki.debian.org/Teams/Cloud/VagrantBaseBoxes):

"The vagrant vbguest plugin is not needed with the Debian boxes and we don't test it.

If you use boxes up to Debian 10 Buster, use the contrib boxes at https://app.vagrantup.com/debian. The contrib boxes already include the needed kernel modules, so you don't have to recompile the modules via the vagrant-vgbuest module. 

If you use Debian 11 Bullseyes and higher, the kernel modules are already included in the box itself, since the kernel modules [are now part of the official kernel releases.](https://kernelnewbies.org/Linux_5.6#Support_for_VirtualBox_guest_shared_folders)

Disabling vbguest with

`config.vbguest.auto_update = false`

disables it for the current Vagrantfile without removing the plugin globally."

I've just tested this approach with debian/bookworm64:
```
Checking for guest additions in VM...
The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
prevent things such as shared folders from working properly. If you see
shared folder errors, please make sure the guest additions within the
virtual machine match the version of VirtualBox you have installed on
your host and reload your VM.

Guest Additions Version: 6.0.0 r127566
VirtualBox Version: 7.0
```
Apart from being stuck with VBox Guest Additions v6.0.x this seems to be good enough for shared directories to work. No idea though how about the support for more recent features (if there were any).

**Comment by 0xbk** [comment]
This issue seems to have been introduced in VirtualBox 7.0.8 (and still an issue in 7.0.10). I downgraded to 7.0.6 and installation of the guest additions works again.

**Comment by Jazzepi** [comment]
> This issue seems to occur with VirtualBox 7.0.8 and 7.0.10. I downgraded to 7.0.6 and everything works with Vagrant 2.3.7.

I was also able to get it to work with VB 7.0.6 Windows 10 host, Ubuntu 20.04 guest
