### ISSUE TITLE
Failure to install VBox 4.2.12 guest additions when X is not installed

### ISSUE THREAD

**Issue by rtkpmcalpine** [dotless-de/vagrant-vbguest#61]
Since upgrading to VirtualBox 4.2.12 (4.2.10 worked fine) I get an error when I bring up my VMs. I've asked about it on the VirtualBox forums but they don't seem to believe it's an issue with VirtualBox.
https://forums.virtualbox.org/viewtopic.php?f=3&t=55166&p=254210#p254210
- VirtualBox 4.2.12
- Mac OS X host
- Ubuntu 12.04 guest
- Vagrant 1.0.7

Here's the error:
Installing Virtualbox Guest Additions 4.2.12 - guest version is 4.2.10
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.2.12 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 4.2.10 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

Installing the Window System drivers ...fail!
(Could not find the X.Org or XFree86 Window System.)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/mnt/VBoxLinuxAdditions.run --nox11

**Comment by stevenroose** [comment]
I also have it with the current latest version in Arch when installing in a RHEL 7.2 server VM. `--nox11` doesn't work either.
