### ISSUE TITLE
Update on Windows 2008 Guest

### ISSUE THREAD

**Issue by ifunky** [dotless-de/vagrant-vbguest#65]
Hi,

I'm trying to the auto update working from my host (Windows 7) to the guest which is Windows 2008 but I receive:

ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantVbguest::Installer::NoInstallerFoundError: translation missing: en.vagrant_vbguest.errors.installer.no_install_script_
for_platform>
ERROR vagrant: translation missing: en.vagrant_vbguest.errors.installer.no_install_script_for_platform
ERROR vagrant: C:/Users/gibbonsd/.vagrant.d/gems/gems/vagrant-vbguest-0.8.0/lib/vagrant-vbguest/installer.rb:87:in `guest_version'

Looks like this isn't supported?  Would I need to write a custom script?

Thanks

Dan

**Comment by lonniev** [comment]
Although it would require pre-installation of chocolatey, this might be part of the solution:

https://chocolatey.org/packages/VBoxGuestAdditions.install

With choco installed, a script could run "choco search -lo VBoxGuestAdditions" to learn which--if any--guest additions were installed and "choco update VBoxGuestAdditions" to update to whatever is latest.
