### ISSUE TITLE
Cancelling Installation (Ubuntu vagrant box from PuppetLabs)

### ISSUE THREAD

**Issue by cdmoye** [dotless-de/vagrant-vbguest#88]
When trying to use the vbguest plugin to update the Ubuntu 13.10 box that is served up by Puppetlabs (in case you want to reproduce the issue), I get the following message:
# 

VirtualBox Guest Additions installer
You appear to have a version of the VBoxGuestAdditions software
on your system which was installed from a different source or using a
different type of installer.  If you installed it from a package from your
Linux distribution or if it is a default part of the system then we strongly
recommend that you cancel this installation and remove it properly before
installing this version.  If this is simply an older or a damaged
installation you may safely proceed.

Do you wish to continue anyway? [yes or no]

Cancelling installation.
# 

Note: I can't choose to "continue anyway" as the plugin quits: 

An error occurred during installation of VirtualBox Guest Additions 4.2.18. Some functionality may not work as intended.

**Comment by c-sonntag** [comment]
Maybe you can go to see my issue at this link : https://github.com/dotless-de/vagrant-vbguest/issues/252#issuecomment-331585965
