### ISSUE TITLE
vbguest can't determine version of Virtual Box Guest Additions

### ISSUE THREAD

**Issue by dawilliams** [dotless-de/vagrant-vbguest#96]
Hello,

I'm trying to get the vbguest plugin to work on a Windows 2012 guest in Virtual Box and keep getting the following message.

"Sorry, don't know how to check guest version of Virtualbox Guest Additions on this platform. Stopping installation." 

I'm looking for some assistance to debug this issue.

I'm using the following:
Mac Machine
  Vagrant 1.3.5
  vagrant-vbguest 0.9.0
  Virtual Box 4.2.18
  Virtual Box Guest Additions 4.2.18

My image was created by veewee

Thank you for your help,

David

**Comment by wickedviking** [comment]
@fnordfish Is this still the case? Windows not being supported I mean?

**Comment by fnordfish** [comment]
@wickedviking I'm afraid it is.
