### ISSUE TITLE
Vbguest additions cancel installation on version mismatch

### ISSUE THREAD

**Issue by davidjb** [dotless-de/vagrant-vbguest#97]
I'm running a Centos 6.4 VM and have installed this plugin (version 0.9.0) and have previously used it to install guest additions without problems, on this specific VM run using Vagrant.  However, I'm now finding that there's a version issue being reported and the plugin cancels installation when prompted.  As it stands, the guest additions were actually installed by this plugin itself, so replacing the installed version should be no issue.  

My output:

```
GuestAdditions versions on your host (4.2.18) and guest (4.2.18 r88780) do not match.
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
Setting up Install Process
Package kernel-devel-2.6.32-358.23.2.el6.x86_64 already installed and latest version
Package gcc-4.4.7-3.el6.x86_64 already installed and latest version
Package 1:make-3.81-20.el6.x86_64 already installed and latest version
Package 4:perl-5.10.1-131.el6_4.x86_64 already installed and latest version
Nothing to do
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Installing Virtualbox Guest Additions 4.2.18 - guest version is 4.2.18 r88780
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.2.18 Guest Additions for Linux............
VirtualBox Guest Additions installer
You appear to have a version of the VBoxGuestAdditions software
on your system which was installed from a different source or using a
different type of installer.  If you installed it from a package from your
Linux distribution or if it is a default part of the system then we strongly
recommend that you cancel this installation and remove it properly before
installing this version.  If this is simply an older or a damaged
installation you may safely proceed.

Do you wish to continue anyway? [yes or no]

Cancelling installation.
An error occurred during installation of VirtualBox Guest Additions 4.2.18. Some functionality may not work as intended.
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /srv
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /srv /srv
Stdout from the command:

Stderr from the command:

mount: Protocol error
```

I've ended up manually re-installing the Guest Additions to solve the issue, such that I can interactively answer "yes" to the prompt asking to override.

**Comment by phpguru** [comment]
Docker, Vagrant, Mac OS X

    GuestAdditions versions on your host (4.3.28) and guest (4.3.26 r98988) do not match.

**Comment by davidjb** [comment]
Still an issue for me (when going back to provisioning using older configuration) on vbguest 0.14.2; Could this be re-opened?  As per your suggestion, @fnordfish if either the uninstaller can be run before trying to install (or just providing an option that accepts the uninstall when prompted), that'd solve the problem.

**Comment by c-sonntag** [comment]
Maybe you can go to see my issue at this link : 
https://github.com/dotless-de/vagrant-vbguest/issues/252#issuecomment-331585965

**Comment by c-sonntag** [comment]
Maybe you can go to see my issue at this link : https://github.com/dotless-de/vagrant-vbguest/issues/252#issuecomment-331585965
