### ISSUE TITLE
plugin fails to install newer guest additions under certain circumstances

### ISSUE THREAD

**Issue by meros** [dotless-de/vagrant-vbguest#99]
I am using the official ubuntu 13.10 cloud image and because of some bugs with virtualbox and mounting I need to update the guest additions as part of the up. You solution is _perfect_. But it fails for me:

```
Installing Virtualbox Guest Additions 4.3.2 - guest version is 4.2.16
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.2 Guest Additions for Linux............
VirtualBox Guest Additions installer
You appear to have a version of the VBoxGuestAdditions software
on your system which was installed from a different source or using a
different type of installer.  If you installed it from a package from your
Linux distribution or if it is a default part of the system then we strongly
recommend that you cancel this installation and remove it properly before
installing this version.  If this is simply an older or a damaged
installation you may safely proceed.

Do you wish to continue anyway? [yes or no]

Cancelling installation.
```

I assume that the problem is that the official image is build with these additions installed from a seperate deb package and the virtualbox installer doesn't want to work with that...

**Comment by c-sonntag** [comment]
Hey everyone!
I have solved this problem with custom class vbguest:installer, inserted in the configuration.
I know, I can directly patch the "vbguest" package, but I'm not an expert in Ruby.
So, in your configuration part, add code like’s it:
```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # [...]

  # -- Patch vbguest --
    class MyVbguestInstaller < VagrantVbguest::Installers::Linux
      def yes
        return 'echo yes\n | '
      end
    end
    config.vbguest.installer = MyVbguestInstaller
  # -- end : Patch vbguest --

  # [...]

end
```
I hope I've helped you.
Christophe.

**Comment by worp1900** [comment]
Curiously, for me it seemed to be enough to have an indication that VBoxGuestAdditions were installed differently before, by the presence of /opt/VBoxGuestAdditions-5.0.16. in the guest.

` sudo rm -rf VBoxGuestAdditions-5.0.16/`
Fixed the problem for me.

This:

    $ vagrant vbguest --iso VBoxGuestAdditions_5.1.0_RC1.iso --do install
    [myVm] GuestAdditions versions on your host (5.1.26) and guest (5.0.16) do not match.
    Loaded plugins: fastestmirror, priorities
    Loading mirror speeds from cached hostfile
     * base: ftp.antilo.de
     * epel: mirror.i3d.net
     * extras: centos.intergenia.de
     * updates: ftp.antilo.de
    523 packages excluded due to repository priority protections
    Package kernel-devel-3.10.0-693.2.2.el7.x86_64 already installed and latest version
    Package gcc-4.8.5-16.el7.x86_64 already installed and latest version
    Package binutils-2.25.1-32.base.el7_4.1.x86_64 already installed and latest version
    Package 1:make-3.82-23.el7.x86_64 already installed and latest version
    Package 4:perl-5.16.3-292.el7.x86_64 already installed and latest version
    Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
    Nothing to do
    Copy iso file VBoxGuestAdditions_5.1.0_RC1.iso into the box /tmp/VBoxGuestAdditions.iso
    mount: /dev/loop0 is write-protected, mounting read-only
    Forcing installation of Virtualbox Guest Additions 5.1.0 - guest version is 5.0.16
    Verifying archive integrity... All good.
    Uncompressing VirtualBox 5.1.0_RC1 Guest Additions for Linux...........
    VirtualBox Guest Additions installer
    You appear to have a version of the VBoxGuestAdditions software
    on your system which was installed from a different source or using a
    different type of installer.  If you installed it from a package from your
    Linux distribution or if it is a default part of the system then we strongly
    recommend that you cancel this installation and remove it properly before
    installing this version.  If this is simply an older or a damaged
    installation you may safely proceed.
    
    Do you wish to continue anyway? [yes or no]
    
    Cancelling installation.
    An error occurred during installation of VirtualBox Guest Additions 5.1.0. Some functionality may not work as intended.
    In most cases it is OK that the "Window System drivers" installation failed.
    Redirecting to /bin/systemctl start vboxadd.service
    Failed to start vboxadd.service: Unit not found.

Became this afterwards:

    $ vagrant vbguest --iso VBoxGuestAdditions_5.1.0_RC1.iso --do install
    [myVm] GuestAdditions versions on your host (5.1.26) and guest (5.0.16) do not match.
    Loaded plugins: fastestmirror, priorities
    Loading mirror speeds from cached hostfile
     * base: ftp.antilo.de
     * epel: mirror.i3d.net
     * extras: centos.intergenia.de
     * updates: ftp.antilo.de
    523 packages excluded due to repository priority protections
    Package kernel-devel-3.10.0-693.2.2.el7.x86_64 already installed and latest version
    Package gcc-4.8.5-16.el7.x86_64 already installed and latest version
    Package binutils-2.25.1-32.base.el7_4.1.x86_64 already installed and latest version
    Package 1:make-3.82-23.el7.x86_64 already installed and latest version
    Package 4:perl-5.16.3-292.el7.x86_64 already installed and latest version
    Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
    Nothing to do
    Copy iso file VBoxGuestAdditions_5.1.0_RC1.iso into the box /tmp/VBoxGuestAdditions.iso
    mount: /dev/loop0 is write-protected, mounting read-only
    Forcing installation of Virtualbox Guest Additions 5.1.0 - guest version is 5.0.16
    Verifying archive integrity... All good.
    Uncompressing VirtualBox 5.1.0_RC1 Guest Additions for Linux...........
    VirtualBox Guest Additions installer
    Copying additional installer modules ...
    Installing additional modules ...
    vboxadd.sh: Building Guest Additions kernel modules.
    vboxadd.sh: Starting the VirtualBox Guest Additions.

    Could not find the X.Org or XFree86 Window System, skipping.
    Redirecting to /bin/systemctl start vboxadd.service

All seems to work now.
